Repository scania-digital-design-system/sdds, pull requests merged in 2021-01, with the labels that each got.

#43 Create azuredevops.yml
  .github/workflows/azuredevops.yml
Labels: Component, Improvement, Theme

#44 Update azuredevops.yml
  .github/workflows/azuredevops.yml
Labels: Improvement

#46 Update azuredevops.yml
  .github/workflows/azuredevops.yml
Labels: Improvement

#47 Update azuredevops.yml
  .github/workflows/azuredevops.yml
Labels: bug

#49 Improvement/workflow pr
  .github/workflows/azuredevops-issue.yml
  .github/workflows/azuredevops-pr.yml
Labels: Improvement

#38 Added story for grid, spacing, new spacing option and more...
  components/.storybook/main.js
  components/.storybook/preview.js
  components/package-lock.json
  components/package.json
  components/src/components/theme/colour.stories.js
  components/src/components/theme/grid.stories.js
  components/src/components/theme/spacing.stories.js
  components/src/components/theme/typography.stories.js
  theme/light/src/styles/core/spacing/spacing-vars.scss
Labels: Component, Improvement, Theme

#40 Improvement - Added lerna
  CONTRIBUTING.md
  components/.storybook/preview.js
  components/package-lock.json
  components/package.json
  components/src/helpers/core.js
  components/stencil.config.ts
  lerna.json
  package-lock.json
  package.json
  theme/light/package-lock.json
  theme/light/package.json
  theme/light/src/styles/core/colour/package-lock.json
  theme/light/src/styles/core/colour/package.json
  theme/light/src/styles/core/grid/package-lock.json
  theme/light/src/styles/core/grid/package.json
  theme/light/src/styles/core/typography/package-lock.json
  theme/light/src/styles/core/typography/package.json
Labels: Improvement

#52 Feature/add scania organisation npm
  components/.storybook/preview.js
  components/package-lock.json
  components/package.json
  components/readme.md
  demo/angular/README.md
  demo/angular/package-lock.json
  demo/angular/package.json
  demo/angular/src/main.ts
  demo/react/README.md
  demo/react/package-lock.json
  demo/react/package.json
  demo/react/src/index.js
  readme.md
  theme/light/package-lock.json
  theme/light/package.json
  theme/light/readme.md
  theme/light/src/styles/core/colour/README.md
  theme/light/src/styles/core/colour/package-lock.json
  theme/light/src/styles/core/colour/package.json
  theme/light/src/styles/core/grid/README.md
  theme/light/src/styles/core/grid/package-lock.json
  theme/light/src/styles/core/grid/package.json
  theme/light/src/styles/core/typography/README.md
  theme/light/src/styles/core/typography/package-lock.json
  theme/light/src/styles/core/typography/package.json
Labels: Feature

#51 AB#251 - Remove bootstrap global
  components/src/components/global-style/global-style.scss
  components/src/components/global-style/global-style.tsx
  components/src/components/icon/icon.stories.js
  components/src/components/theme/button.stories.js
  components/src/components/theme/textfield.stories.js
  components/src/patterns/cookie/cookie.scss
  components/src/patterns/cookie/cookie.tsx
  components/src/patterns/cookie/readme.md
  theme/light/src/styles/core/typography/_tokens.scss
  theme/light/src/styles/patterns/c-cookie.scss
  theme/light/src/styles/patterns/c-dropdown.scss
  theme/light/src/styles/patterns/c-global-style.scss
  theme/light/src/styles/patterns/c-table.scss
  theme/light/src/styles/patterns/c-theme.scss
Labels: Component, Feature, Theme

#53 Bug/fix label bug duplicate
  .github/workflows/azuredevops-issue.yml
  .github/workflows/azuredevops-pr.yml
Labels: bug

#54 AB#329 - Adding netlify
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/azuredevops-pr.yml
  components/package-lock.json
  components/package.json
  package.json
  theme/light/package-lock.json
  theme/light/src/styles/core/colour/package-lock.json
  theme/light/src/styles/core/grid/package-lock.json
  theme/light/src/styles/core/typography/_tokens.scss
  theme/light/src/styles/core/typography/package-lock.json
Labels: Component, Feature, Theme

#58 bug - fix for type-scale value
  theme/light/src/styles/core/typography/_tokens.scss
Labels: Theme, bug

#56 Remove c-global and update theme mode
  components/package.json
  components/src/components/global-style/global-style.scss
  components/src/components/global-style/global-style.tsx
  components/src/components/global-style/readme.md
  components/src/components/modal/modal.tsx
  components/src/components/theme/theme.tsx
  components/src/global.ts
  components/src/helpers/index.js
  components/src/store.ts
  theme/light/gulpfile.babel.js
  theme/light/src/styles/patterns/c-global-style.scss
  theme/light/src/styles/patterns/c-theme.scss
  theme/light/src/styles/utilities/typography.scss
Labels: Improvement
