Repository scania-digital-design-system/sdds, pull requests merged in 2021-04, with the labels that each got.

#114 Improvement/update demo angular
  components/package-lock.json
  demo/angular/.editorconfig
  demo/angular/.gitignore
  demo/angular/PULL_REQUEST_TEMPLATE.md
  demo/angular/README.md
  demo/angular/angular.json
  demo/angular/e2e/protractor.conf.js
  demo/angular/e2e/src/app.e2e-spec.ts
  demo/angular/e2e/src/app.po.ts
  demo/angular/e2e/tsconfig.json
  demo/angular/karma.conf.js
  demo/angular/package-lock.json
  demo/angular/package.json
  demo/angular/src/.nojekyll
  demo/angular/src/404.html
  demo/angular/src/app/app-routing.module.ts
  demo/angular/src/app/app.component.html
  demo/angular/src/app/app.component.spec.ts
  demo/angular/src/app/app.component.ts
  demo/angular/src/app/app.module.ts
  demo/angular/src/app/components/header/header.component.html
  demo/angular/src/app/components/header/header.component.scss
  demo/angular/src/app/components/header/header.component.spec.ts
  demo/angular/src/app/components/header/header.component.ts
  demo/angular/src/app/components/main/main.component.html
  demo/angular/src/app/components/main/main.component.scss
  demo/angular/src/app/components/main/main.component.spec.ts
  demo/angular/src/app/components/main/main.component.ts
  demo/angular/src/app/home/home.component.html
  demo/angular/src/app/home/home.component.scss
  demo/angular/src/app/home/home.component.ts
  demo/angular/src/app/info/info-routing.module.ts
  demo/angular/src/app/info/info.component.ts
  demo/angular/src/app/info/info.module.ts
  demo/angular/src/app/info/subpages/form.component.ts
  demo/angular/src/app/info/subpages/list.component.ts
  demo/angular/src/app/info/subpages/modal.component.ts
  demo/angular/src/app/info/subpages/table.component.html
  demo/angular/src/app/info/subpages/table.component.ts
  demo/angular/src/app/items.ts
  demo/angular/src/app/navigation/navigation.component.html
  demo/angular/src/app/navigation/navigation.component.ts
  demo/angular/src/app/notfound/notfound.component.ts
  demo/angular/src/browserslist
  demo/angular/src/favicon.ico
  demo/angular/src/index.html
  demo/angular/src/main.ts
  demo/angular/src/polyfills.ts
  demo/angular/src/styles.css
  demo/angular/src/styles.scss
  demo/angular/src/test.ts
  demo/angular/src/tslint.json
  demo/angular/tsconfig-es5.app.json
  demo/angular/tsconfig.app.json
  demo/angular/tsconfig.json
  demo/angular/tsconfig.spec.json
  demo/angular/tslint.json
  readme.md
Labels: Improvement

#122 Bug/Fix bug in textarea for condition if no label
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.tsx
Labels: Component, bug

#123 Hotfix blue-800 --> blue-900
  demo/HTML/html.css
Labels: Improvement

#124 AB#719 Publish from sprint 6
  components/package-lock.json
  components/package.json
  theme/core/grid/package-lock.json
  theme/core/grid/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature

#126 Feature - Modal component v1
  components/.storybook/preview.js
  components/package-lock.json
  components/package.json
  components/src/components/modal/modal.scss
  components/src/components/modal/modal.stories.js
  components/src/components/modal/modal.tsx
  components/src/components/modal/readme.md
  components/src/components/theme/theme.scss
  components/src/patterns/cookie/readme.md
  theme/core/spacing/_vars.scss
  theme/core/spacing/spacing-vars.scss
  theme/light/src/components/_link.scss
  theme/light/src/components/_modal.scss
  theme/light/src/patterns/c-modal.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature

#128 AB#758 Publish from sprint 7
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature

#131 AB#688 Remove font load duplication in scania theme light
  demo/HTML/html.css
  demo/HTML/package-lock.json
  theme/core/typography/_selectors.scss
  theme/core/typography/_typography.scss
  theme/light/src/_variables.scss
  theme/light/src/theme/sdds-theme.scss
Labels: bug

#130 AB#507 Fix#88 Use document readyState to fix FoUC
  components/src/helpers/core.js
  components/src/helpers/index.js
Labels: bug
