Repository scania-digital-design-system/sdds, pull requests merged in 2021-05, with the labels that each got.

#134 AB#785 Bug - dropdown angular error trying to loop an object
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/dropdown/dropdown.tsx
Labels: Component, bug

#135 AB#687 Fixed the bug regarding the distance with tooltip and <sdds-button>
  components/src/components/button/button.scss
  components/src/components/button/button.stories.js
  components/src/components/tooltips/tooltip.scss
  components/src/components/tooltips/tooltip.stories.js
  components/src/components/tooltips/tooltip.tsx
Labels: Component, bug

#138 Update azuredevops-issue.yml
  .github/workflows/azuredevops-issue.yml
Labels: Improvement

#140 Improvement/remove_old_links
  demo/angular/README.md
Labels: Improvement

#144 AB#801 Change link colour
  theme/light/src/components/_link.scss
Labels: Improvement

#145 AB#803 Feature - Toasts component
  components/src/components/theme/theme.scss
  components/src/components/toast/toast.scss
  components/src/components/toast/toast.stories.js
  theme/light/src/components/_toast.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature

#146 Feature - Banner component styling
  components/src/components/accordion/accordion.stories.js
  components/src/components/banner/banner.scss
  components/src/components/banner/banner.stories.js
  components/src/components/breadcrumb/breadcrumb.stories.js
  components/src/components/button/button.stories.js
  components/src/components/checkbox/checkbox.stories.js
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/icon/icon.stories.js
  components/src/components/link/link.stories.js
  components/src/components/radio-button/radio-button.stories.js
  components/src/components/textarea/textarea.stories.js
  components/src/components/theme/colour.stories.js
  components/src/components/theme/grid.stories.js
  components/src/components/theme/spacing.stories.js
  components/src/components/theme/theme.scss
  components/src/components/theme/typography.stories.js
  components/src/components/toast/toast.scss
  components/src/components/toggle/toggle.stories.js
  components/src/components/tooltips/tooltip.stories.js
  components/src/patterns/dealer-header/dealer-header.stories.js
  components/src/patterns/footer/footer.stories.js
  components/src/patterns/header/header.stories.js
  components/src/patterns/navigation/navigation.stories.js
  theme/light/src/components/_banner.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature

#148 AB#830 Publish from sprint 9
  components/package-lock.json
  components/package.json
  readme.md
  theme/core/icons/package-lock.json
  theme/core/icons/package.json
  theme/core/typography/package-lock.json
  theme/core/typography/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Component, Feature, Theme
