Repository scania-digital-design-system/sdds, pull requests merged in 2021-08, with the labels that each got.

#172 AB#914 Feature/side menu
  components/package-lock.json
  components/src/components/theme/theme.scss
  components/src/patterns/header/_mixins.scss
  components/src/patterns/header/_navbar-brand.scss
  components/src/patterns/header/_navbar-collapsible.scss
  components/src/patterns/header/_navbar-menu-item.scss
  components/src/patterns/header/_navbar-toolbar-menu.scss
  components/src/patterns/header/header.scss
  components/src/patterns/navigation/navigation.stories.js
  components/src/patterns/side-menu/side-menu.scss
  components/src/patterns/side-menu/side-menu.stories.js
  demo/HTML/icons.html
  demo/HTML/index.html
  demo/HTML/side-menu.html
  theme/light/src/patterns/header.scss
  theme/light/src/patterns/side-menu.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Feature, Component

#178 Fix issue with range slider breaking storybook
  components/package-lock.json
  components/src/components/card/card.stories.js
  components/src/components/divider/divider.stories.js
  components/src/components/icon/icon.stories.js
  package-lock.json
  theme/core/grid/package-lock.json
  theme/light/package-lock.json
Labels: Bug, Component

#176 AB#854 Feature/footer
  components/src/components/theme/fullpage.stories.js
  components/src/components/theme/theme.scss
  components/src/patterns/footer/footer.e2e.ts
  components/src/patterns/footer/footer.scss
  components/src/patterns/footer/footer.spec.ts
  components/src/patterns/footer/footer.stories.js
  components/src/patterns/footer/footer.tsx
  components/src/patterns/side-menu/side-menu.scss
  demo/HTML/html.css
  demo/HTML/side-menu.html
  theme/light/src/patterns/footer.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Feature, Component

#160 added more icons
  theme/core/icons/src/svg/scania-battery-car.svg
  theme/core/icons/src/svg/scania-bird.svg
  theme/core/icons/src/svg/scania-business.svg
  theme/core/icons/src/svg/scania-business_development.svg
  theme/core/icons/src/svg/scania-car.svg
  theme/core/icons/src/svg/scania-charge_management_system.svg
  theme/core/icons/src/svg/scania-chemicals.svg
  theme/core/icons/src/svg/scania-cover_cough.svg
  theme/core/icons/src/svg/scania-dont_touch_face.svg
  theme/core/icons/src/svg/scania-electricity_contract.svg
  theme/core/icons/src/svg/scania-electricity_production.svg
  theme/core/icons/src/svg/scania-gastruck.svg
  theme/core/icons/src/svg/scania-keep_distance.svg
  theme/core/icons/src/svg/scania-local_surrounding.svg
  theme/core/icons/src/svg/scania-market.svg
  theme/core/icons/src/svg/scania-motorbike.svg
  theme/core/icons/src/svg/scania-no_handshake.svg
  theme/core/icons/src/svg/scania-raw_material.svg
  theme/core/icons/src/svg/scania-scale.svg
  theme/core/icons/src/svg/scania-sds.svg
  theme/core/icons/src/svg/scania-shopping_cart.svg
  theme/core/icons/src/svg/scania-solar_power_cell.svg
  theme/core/icons/src/svg/scania-stanna_hemma.svg
  theme/core/icons/src/svg/scania-stay_at_home.svg
  theme/core/icons/src/svg/scania-thunder.svg
  theme/core/icons/src/svg/scania-toll_gate.svg
  theme/core/icons/src/svg/scania-transformer_station.svg
  theme/core/icons/src/svg/scania-transmission_network.svg
  theme/core/icons/src/svg/scania-tree.svg
  theme/core/icons/src/svg/scania-vacuum_cleaner.svg
  theme/core/icons/src/svg/scania-warehouse.svg
  theme/core/icons/src/svg/scania-wash_hands.svg
  theme/core/icons/src/svg/scania-workshop.svg
Labels: Improvement, Theme

#177 Changed application title type to Scania Sans Headline #946
  components/src/patterns/header/_navbar-brand.scss
Labels: Improvement

#183 release next icons
  components/package-lock.json
  theme/core/icons/package-lock.json
  theme/core/icons/package.json
Labels: Improvement, Theme
