Repository scania-digital-design-system/sdds, pull requests merged in 2021-11, with the labels that each got.

#222 Fix issue rights on Mac for branch #216
  .husky/pre-commit
Labels: Bug, Improvement, Theme, Component

#220 Header: focus/tabbing + border jumpy content fix
  components/src/patterns/header/_mixins.scss
  components/src/patterns/header/_navbar-menu-item.scss
  components/src/patterns/header/_navbar-toolbar-menu.scss
  components/src/patterns/header/header.scss
  components/src/patterns/header/header.stories.js
  components/src/patterns/side-menu/side-menu.scss
  components/src/patterns/side-menu/side-menu.stories.js
Labels: Bug, Improvement

#224 Publish
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature, Theme, Component

#227 port and text change to differentiate angular version in browser
  demo/angular/angular11/README.md
  demo/angular/angular11/package.json
  demo/angular/angular11/src/app/components/main/main.component.html
  demo/angular/angular12/README.md
  demo/angular/angular12/package.json
  demo/angular/angular12/src/app/components/main/main.component.html
  demo/angular/angular13/package.json
  demo/angular/angular13/src/app/components/main/main.component.html
Labels: Improvement

#230 Prettier in demo/angular
  demo/angular/angular12/angular.json
  demo/angular/angular12/src/app/app.component.spec.ts
  demo/angular/angular12/src/app/app.component.ts
  demo/angular/angular12/src/app/app.module.ts
  demo/angular/angular12/src/environments/environment.prod.ts
  demo/angular/angular12/src/environments/environment.ts
  demo/angular/angular12/src/index.html
  demo/angular/angular12/src/polyfills.ts
  demo/angular/angular12/src/test.ts
  demo/angular/angular12/tsconfig.app.json
  demo/angular/angular12/tsconfig.json
  demo/angular/angular12/tsconfig.spec.json
  demo/angular/angular13/angular.json
  demo/angular/angular13/src/app/app.component.spec.ts
  demo/angular/angular13/src/app/app.component.ts
  demo/angular/angular13/src/app/app.module.ts
  demo/angular/angular13/src/environments/environment.prod.ts
  demo/angular/angular13/src/environments/environment.ts
  demo/angular/angular13/src/index.html
  demo/angular/angular13/src/polyfills.ts
  demo/angular/angular13/src/test.ts
  demo/angular/angular13/tsconfig.app.json
  demo/angular/angular13/tsconfig.json
  demo/angular/angular13/tsconfig.spec.json
  theme/light/package-lock.json
Labels: Improvement

#225 Open modal with multiple buttons
  components/src/components/modal/modal.stories.js
  components/src/components/modal/modal.tsx
Labels: Improvement

#228 mobile navigation menu in header fix
  components/src/patterns/header/_navbar-collapsible.scss
Labels: Improvement

#232 Improvement/side menu in React demo
  demo/HTML/package-lock.json
  demo/HTML/side-menu.html
  demo/react/package-lock.json
  demo/react/src/App.js
  demo/react/src/components/header/Header.js
  demo/react/src/components/sideMenu/SideMenu.js
  demo/react/src/components/sideMenu/components/IconButton/IconButton.js
  demo/react/src/components/sideMenu/components/sideMenuDropdownItem/sideMenuDropdownItem.js
  demo/react/src/components/sideMenu/components/sideMenuItem/SideMenuItem.js
  demo/react/src/index.css
Labels: Improvement

#229 Utility classes
  components/src/components/theme/theme.scss
  components/src/helpers/_utility-classes.scss
Labels: Feature, Component

#234 Improvement - gulp file improvement
  .prettierignore
  theme/core/spacing/spacing-vars.scss
  theme/core/typography/typography-vars.scss
  theme/light/gulpfile.babel.js
Labels: Improvement, Theme

#236 Scale up for second level values of utility classes
  components/src/helpers/_utility-classes.scss
Labels: Improvement

#237 fix bug dropdown 7 items and update examples
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.stories.js
  components/src/patterns/header/header.stories.js
  components/stencil.config.ts
  demo/HTML/index.html
  demo/HTML/package-lock.json
  package.json
Labels: Bug, Component

#240 Update PULL_REQUEST_TEMPLATE file
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#241 Improvement - Fix button story not showing icon in basic example
  components/src/components/button/button.stories.js
Labels: Improvement
