Repository scania-digital-design-system/sdds, pull requests merged in 2021-06, with the labels that each got.

#149 Feature - on white bg + some more updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  components/.storybook/main.js
  components/.storybook/preview.js
  components/package-lock.json
  components/package.json
  components/src/components/accordion/accordion.scss
  components/src/components/dropdown/dropdown.scss
  components/src/components/icon/icon.tsx
  components/src/components/icon/readme.md
  demo/HTML/html.css
  demo/HTML/index.html
  demo/HTML/package-lock.json
  demo/HTML/package.json
  demo/angular/package-lock.json
  demo/angular/package.json
  demo/angular/src/app/components/form/input/input-component.ts
  demo/angular/src/app/components/main/main.component.html
  demo/angular/src/app/components/main/main.component.scss
  demo/angular/src/main.ts
  demo/react/README.md
  demo/react/package-lock.json
  demo/react/package.json
  demo/react/src/components/main/Main.css
  demo/react/src/components/main/Main.js
  demo/react/src/index.js
  demo/vue/README.md
  demo/vue/package-lock.json
  demo/vue/package.json
  demo/vue/src/components/Main.vue
  theme/light/src/components/_accordion.scss
  theme/light/src/components/_cards.scss
  theme/light/src/components/_dropdowns.scss
  theme/light/src/components/_textfields.scss
Labels: Improvement, Theme

#147 AB#804 Feature/header
  components/src/components/theme/theme.scss
  components/src/patterns/dealer-header/dealer-header.stories.js
  components/src/patterns/dealer-header/readme.md
  components/src/patterns/header/_mixins.scss
  components/src/patterns/header/_navbar-brand.scss
  components/src/patterns/header/_navbar-collapsible.scss
  components/src/patterns/header/_navbar-global-menu.scss
  components/src/patterns/header/_navbar-menu-item.scss
  components/src/patterns/header/header.e2e.ts
  components/src/patterns/header/header.scss
  components/src/patterns/header/header.spec.ts
  components/src/patterns/header/header.stories.js
  components/src/patterns/header/header.tsx
  components/src/patterns/header/readme.md
  theme/light/gulpfile.babel.js
  theme/light/src/patterns/header.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature

#151 Feature - Release of sprint 10
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature

#154 bug - Added back the banner import
  components/src/components/theme/theme.scss
Labels: bug

#156 Publish banner fix missing import
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: bug

#159 AB#848 Improvement/form fields
  components/src/components/dropdown/_dropdown-core.scss
  components/src/components/dropdown/dropdown-select.scss
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/readme.md
  components/src/components/textfield/textfield.tsx
  components/src/components/theme/theme.scss
  demo/angular/package-lock.json
  demo/angular/src/app/app-routing.module.ts
  demo/angular/src/app/app.module.ts
  demo/angular/src/app/components/form/dropdown/dropdown.component.html
  demo/angular/src/app/components/form/dropdown/dropdown.component.ts
  demo/angular/src/app/components/form/form.component.html
  demo/angular/src/app/components/form/form.component.scss
  demo/angular/src/app/components/form/form.component.ts
  demo/angular/src/app/components/form/input/input-component.html
  demo/angular/src/app/components/header/header.component.html
  demo/angular/src/app/components/home/home.component.html
  demo/angular/src/app/components/home/home.component.ts
  demo/angular/src/app/components/main/main.component.html
  demo/angular/src/app/components/main/main.component.scss
  demo/react/package-lock.json
  demo/react/package.json
  demo/react/src/App.js
  demo/react/src/components/form/Form.js
  demo/react/src/components/header/Header.css
  demo/react/src/components/header/Header.js
  demo/react/src/components/home/Home.js
  demo/react/src/components/main/Main.css
  demo/react/src/components/main/Main.js
  demo/react/src/index.css
  theme/light/src/components/_dropdowns.scss
Labels: Component, Improvement, Theme

#165 AB#873 Bug - slot button react
  components/package-lock.json
  components/src/components/modal/_modal-core.scss
  components/src/components/modal/modal-native.scss
  components/src/components/modal/modal.scss
  components/src/components/modal/modal.stories.js
  components/src/components/modal/modal.tsx
  components/src/components/modal/readme.md
  components/src/components/theme/theme.scss
  demo/angular/package-lock.json
  demo/angular/src/app/components/home/home.component.html
  demo/react/package-lock.json
  demo/react/src/components/home/Home.js
Labels: bug

#166 AB#818 Add unique id for each dropdown event listener
  components/src/components/dropdown/dropdown.tsx
Labels: Component, bug

#168 AB#893 Feature/badges
  components/src/components/badges/badges-component.tsx
  components/src/components/badges/badges.scss
  components/src/components/badges/badges.stories.js
  components/src/components/badges/readme.md
  demo/angular/src/app/components/home/home.component.html
  demo/react/package-lock.json
  theme/light/src/components/_badges.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature, Theme

#170 AB#920 Publish from Sprint 12
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature
