Repository scania-digital-design-system/sdds, pull requests merged in 2021-12, with the labels that each got.

#243 fix(accordion): reset prop for right-padding
  components/package-lock.json
  components/package.json
  components/src/components/accordion/accordion-item.tsx
  components/src/components/accordion/accordion.scss
  components/src/components/accordion/accordion.stories.js
  components/src/components/accordion/readme.md
Labels: Improvement

#248 fix(textarea): border-bottom color
  components/src/components/textarea/textarea.scss
  components/src/components/textfield/textfield.scss
  theme/light/src/components/_textfields.scss
Labels: Improvement

#250 feat(link): add class for controling underline
  components/src/components/card/card.stories.js
  components/src/components/link/link.scss
  components/src/components/link/link.stories.js
Labels: Feature

#251 fix(starting-sdds): bug running sdds the first time
  package.json
Labels: Bug

#253 feat(release): commit containg the release package.json
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature, Theme, Component

#254 Improvement/angular side menu demo
  components/src/components/accordion/accordion.scss
  demo/angular/angular11/package-lock.json
  demo/angular/angular11/src/app/app.component.html
  demo/angular/angular11/src/app/app.component.scss
  demo/angular/angular11/src/app/app.component.ts
  demo/angular/angular11/src/app/app.module.ts
  demo/angular/angular11/src/app/components/header/header.component.html
  demo/angular/angular11/src/app/components/header/header.component.ts
  demo/angular/angular11/src/app/components/main/main.component.html
  demo/angular/angular11/src/app/components/side-menu/icon-button/icon-button.component.html
  demo/angular/angular11/src/app/components/side-menu/icon-button/icon-button.component.scss
  demo/angular/angular11/src/app/components/side-menu/icon-button/icon-button.component.spec.ts
  demo/angular/angular11/src/app/components/side-menu/icon-button/icon-button.component.ts
  demo/angular/angular11/src/app/components/side-menu/side-menu.component.html
  demo/angular/angular11/src/app/components/side-menu/side-menu.component.scss
  demo/angular/angular11/src/app/components/side-menu/side-menu.component.spec.ts
  demo/angular/angular11/src/app/components/side-menu/side-menu.component.ts
  demo/angular/angular12/package-lock.json
  demo/angular/angular12/src/app/app.component.html
  demo/angular/angular12/src/app/app.component.scss
  demo/angular/angular12/src/app/app.component.ts
  demo/angular/angular12/src/app/app.module.ts
  demo/angular/angular12/src/app/components/header/header.component.html
  demo/angular/angular12/src/app/components/header/header.component.ts
  demo/angular/angular12/src/app/components/side-menu/icon-button/icon-button.component.html
  demo/angular/angular12/src/app/components/side-menu/icon-button/icon-button.component.scss
  demo/angular/angular12/src/app/components/side-menu/icon-button/icon-button.component.spec.ts
  demo/angular/angular12/src/app/components/side-menu/icon-button/icon-button.component.ts
  demo/angular/angular12/src/app/components/side-menu/side-menu.component.html
  demo/angular/angular12/src/app/components/side-menu/side-menu.component.scss
  demo/angular/angular12/src/app/components/side-menu/side-menu.component.spec.ts
  demo/angular/angular12/src/app/components/side-menu/side-menu.component.ts
  demo/angular/angular13/package-lock.json
  demo/angular/angular13/src/app/app.component.html
  demo/angular/angular13/src/app/app.component.scss
  demo/angular/angular13/src/app/app.component.ts
  demo/angular/angular13/src/app/app.module.ts
  demo/angular/angular13/src/app/components/header/header.component.html
  demo/angular/angular13/src/app/components/header/header.component.ts
  demo/angular/angular13/src/app/components/side-menu/icon-button/icon-button.component.html
  demo/angular/angular13/src/app/components/side-menu/icon-button/icon-button.component.scss
  demo/angular/angular13/src/app/components/side-menu/icon-button/icon-button.component.spec.ts
  demo/angular/angular13/src/app/components/side-menu/icon-button/icon-button.component.ts
  demo/angular/angular13/src/app/components/side-menu/side-menu.component.html
  demo/angular/angular13/src/app/components/side-menu/side-menu.component.scss
  demo/angular/angular13/src/app/components/side-menu/side-menu.component.spec.ts
  demo/angular/angular13/src/app/components/side-menu/side-menu.component.ts
  package-lock.json
Labels: Improvement

#256 Improvement - expand and hide side menu on mobile view in React
  demo/react/src/App.js
  demo/react/src/components/header/Header.js
  demo/react/src/components/sideMenu/SideMenu.js
Labels: Improvement
