Repository scania-digital-design-system/sdds, pull requests merged in 2021-03, with the labels that each got.

#85 AB#474 Feature/dropdown
  components/src/components/button/readme.md
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/dropdown.tsx
  components/src/components/dropdown/readme.md
  components/src/components/link/link.scss
  components/src/components/table/readme.md
  theme/light/src/components/_dropdowns.scss
  theme/light/src/patterns/c-theme.scss
Labels: Component, Feature, Theme

#87 AB#474 Feature/dropdown filter
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/dropdown.tsx
  components/src/components/dropdown/readme.md
  components/src/patterns/dropdown-filter/dropdown-filter.tsx
  components/src/patterns/dropdown-filter/readme.md
  theme/light/src/components/_dropdowns.scss
Labels: Component, Feature, Theme

#93 Fix z-index for dropdown
  components/src/components/dropdown/dropdown.scss
Labels: bug

#94 Feature/publish patch
  components/package-lock.json
  components/package.json
Labels: Feature

#89 AB#476 Added textarea styling
  components/.storybook/preview.js
  components/package-lock.json
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.scss
  components/src/components/textarea/textarea.stories.js
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/textfield.scss
  theme/light/src/components/_textfields.scss
Labels: Component, Feature, Theme

#95 AB#520 Fix dropdown behaviour
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/dropdown.tsx
  components/src/components/dropdown/readme.md
  components/src/patterns/dropdown-filter/dropdown-filter.tsx
Labels: Component, bug

#98 AB#519 Add spacing vars into grid package
  theme/core/grid/_grid.scss
Labels: Improvement, Theme

#96 AB#518 Improvement/change sdds prefix in theme
  theme/core/_prefix.scss
  theme/core/colour/_colour.scss
  theme/core/colour/_vars.scss
  theme/core/grid/_mixins.scss
  theme/core/typography/_typography.scss
  theme/core/typography/compile.js
  theme/light/src/components/_accordion.scss
  theme/light/src/components/_breadcrumb.scss
  theme/light/src/components/_button.scss
  theme/light/src/components/_checkbox.scss
  theme/light/src/components/_dropdowns.scss
  theme/light/src/components/_link.scss
  theme/light/src/components/_radio-button.scss
  theme/light/src/components/_textfields.scss
  theme/light/src/components/_toggle.scss
  theme/light/src/patterns/c-dropdown.scss
  theme/light/src/patterns/c-theme.scss
Labels: Improvement, Theme

#97 AB#518 Change prefix in components
  components/src/components/accordion/accordion.scss
  components/src/components/breadcrumb/breadcrumb.scss
  components/src/components/button/button.scss
  components/src/components/checkbox/checkbox.scss
  components/src/components/divider/divider.scss
  components/src/components/dropdown/dropdown.scss
  components/src/components/link/link.scss
  components/src/components/radio-button/radio-button.scss
  components/src/components/textfield/textfield.scss
  components/src/components/toggle/toggle.scss
  components/src/helpers/style-helpers.scss
Labels: Component, Improvement

#99 AB#480 Improvement change c theme to sdds theme
  components/readme.md
  components/src/components/accordion/accordion.stories.js
  components/src/components/breadcrumb/breadcrumb.stories.js
  components/src/components/button/button.stories.js
  components/src/components/checkbox/checkbox.stories.js
  components/src/components/divider/divider.stories.js
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/icon/icon.stories.js
  components/src/components/link/link.stories.js
  components/src/components/modal/modal.tsx
  components/src/components/modal/readme.md
  components/src/components/radio-button/radio-button.stories.js
  components/src/components/textarea/textarea.scss
  components/src/components/textfield/textfield.stories.js
  components/src/components/theme/colour.stories.js
  components/src/components/theme/grid.stories.js
  components/src/components/theme/readme.md
  components/src/components/theme/spacing.stories.js
  components/src/components/theme/theme.tsx
  components/src/components/theme/typography.stories.js
  components/src/components/toggle/toggle.stories.js
  components/src/helpers/core.js
  components/src/helpers/index.js
  components/src/patterns/content/content.tsx
  components/src/patterns/content/readme.md
  components/src/patterns/cookie/cookie.tsx
  components/src/patterns/cookie/readme.md
  components/src/patterns/dealer-header/dealer-header.stories.js
  components/src/patterns/footer/footer.stories.js
  components/src/patterns/footer/footer.tsx
  components/src/patterns/footer/readme.md
  components/src/patterns/header/header.stories.js
  components/src/patterns/header/header.tsx
  components/src/patterns/header/readme.md
  components/src/patterns/navigation/navigation.stories.js
  components/src/patterns/navigation/navigation.tsx
  components/src/patterns/navigation/readme.md
  demo/angular/README.md
  demo/react/README.md
  readme.md
  theme/light/gulpfile.babel.js
  theme/light/readme.md
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Improvement

#86 AB#298 Feature/tooltip
  components/package-lock.json
  components/package.json
  components/src/components/tooltips/readme.md
  components/src/components/tooltips/tooltip.scss
  components/src/components/tooltips/tooltip.stories.js
  components/src/components/tooltips/tooltip.tsx
  theme/light/src/components/_tooltip.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature, Theme

#101 AB# 294 Feature - card component
  components/.storybook/assets/image/card-img-left.png
  components/.storybook/assets/image/card-img.png
  components/src/components/card/card.scss
  components/src/components/card/card.stories.js
  components/src/components/card/card.tsx
  components/src/components/card/readme.md
  components/src/components/dropdown/readme.md
  components/src/components/theme/theme.scss
  theme/light/src/_variables.scss
  theme/light/src/components/_cards.scss
  theme/light/src/components/_link.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component, Feature

#102 Fix docs & sdds-theme in textarea
  components/src/components/textarea/textarea.stories.js
  readme.md
Labels: Improvement

#104 Publish
  components/package-lock.json
  components/package.json
  theme/core/grid/package-lock.json
  theme/core/grid/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature

#105 Hotfixed z-index for tooltip
  components/src/components/tooltips/tooltip.scss
Labels: Component, bug

#107 Publish
  components/package-lock.json
  components/package.json
Labels: Feature

#109 update readme with npm link to org
  readme.md
Labels: Component, Improvement, Theme

#110 Improvement/update demo html
  demo/HTML/README.md
  demo/HTML/html.css
  demo/HTML/index.html
  demo/HTML/package-lock.json
  demo/HTML/package.json
Labels: Improvement
