Repository scania-digital-design-system/sdds, pull requests merged in 2021-09, with the labels that each got.

#184 Feature - Big updated colours
  components/src/components/accordion/accordion.stories.js
  components/src/components/radio-button/radio-button.scss
  components/src/components/theme/colour.stories.js
  components/src/components/toast/toast.scss
  components/src/patterns/footer/footer.scss
  theme/core/colour/_tokens.scss
  theme/light/src/_variables.scss
  theme/light/src/components/_accordion.scss
  theme/light/src/components/_banner.scss
  theme/light/src/components/_breadcrumb.scss
  theme/light/src/components/_button.scss
  theme/light/src/components/_cards.scss
  theme/light/src/components/_checkbox.scss
  theme/light/src/components/_divider.scss
  theme/light/src/components/_dropdowns.scss
  theme/light/src/components/_link.scss
  theme/light/src/components/_modal.scss
  theme/light/src/components/_radio-button.scss
  theme/light/src/components/_spinner.scss
  theme/light/src/components/_textfields.scss
  theme/light/src/components/_toast.scss
  theme/light/src/components/_toggle.scss
  theme/light/src/components/_tooltip.scss
  theme/light/src/patterns/footer.scss
  theme/light/src/patterns/header.scss
  theme/light/src/patterns/side-menu.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Feature, Theme, Component

#192 Improvement - update packages in demo
  components/package-lock.json
  components/package.json
  theme/core/colour/package-lock.json
  theme/core/colour/package.json
  theme/core/icons/package-lock.json
  theme/core/icons/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature, Theme, Component

#196 Improvement - Breadcrumb fix colours, pointer and story having extra space
  components/src/components/breadcrumb/breadcrumb.scss
  components/src/components/breadcrumb/breadcrumb.stories.js
  theme/light/src/components/_breadcrumb.scss
Labels: Improvement, Theme, Component

#195 Bug/eslint fixes
  components/.eslintignore
  components/.eslintrc.js
  components/.eslintrc.json
  components/.husky/pre-commit
  components/.prettierrc
  components/.travis.yml
  components/package-lock.json
  components/package.json
  components/src/global.ts
Labels: Bug, Component

#194 Improvement - Button colours for icons and some other small fixes
  components/src/components/button/button.scss
  components/src/components/button/button.stories.js
Labels: Improvement, Theme, Component

#191 Improvement/tooltip
  components/src/components/tooltips/readme.md
  components/src/components/tooltips/tooltip.stories.js
  components/src/components/tooltips/tooltip.tsx
Labels: Improvement

#198 Fix for icon component not finding module
  components/src/components/hello-world/hello-world.e2e.ts
  components/src/components/hello-world/hello-world.scss
  components/src/components/hello-world/hello-world.spec.ts
  components/src/components/hello-world/hello-world.tsx
  components/src/components/hello-world/readme.md
  components/src/components/icon/icon.stories.js
  components/src/components/icon/icon.tsx
  components/src/components/icon/readme.md
  components/src/global/variables.css
  components/stencil.config.ts
Labels: Bug, Breaking, Component

#197 Feature/data table
  components/src/components/table/table
  components/src/components/table/table.scss
  components/src/components/table/table.stories.js
  components/src/components/theme/theme.scss
  theme/light/src/components/_table.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component

#199 Publish
  components/package-lock.json
  components/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: Feature, Theme, Component

#200 Improvement - Update on white background states for button
  components/src/components/icon/icon.stories.js
  theme/light/src/components/_button.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Improvement, Theme, Component

#202 Improvement- enabling all eslint rules
  components/.eslintignore
  components/.eslintrc.json
  components/src/components/accordion/accordion-item.tsx
  components/src/components/card/card.tsx
  components/src/components/modal/modal.tsx
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/textfield.tsx
  components/src/components/theme/grid.stories.js
  components/src/global.ts
Labels: Improvement, Component

#203 Feature - sass lint added from both theme and components
  .stylelintrc.json
  .travis.yml
  package-lock.json
  package.json
Labels: Feature, Theme, Component
