Repository scania-digital-design-system/sdds, pull requests merged in 2022-04, with the labels that each got.

#345 feat(utilites): more utilities added
  components/src/helpers/_utility-classes.scss
Labels: Theme

#342 perf: bump versions for a lot of packages for node v16
  .eslintrc.json
  components/package-lock.json
  components/package.json
  components/src/patterns/content/content.e2e.ts
  components/src/patterns/content/content.scss
  components/src/patterns/content/content.spec.ts
  components/src/patterns/content/content.tsx
  components/src/patterns/content/readme.md
  components/src/patterns/cookie/cookie.scss
  components/src/patterns/cookie/cookie.tsx
  components/src/patterns/cookie/readme.md
  components/src/patterns/dealer-header/dealer-header.e2e.ts
  components/src/patterns/dealer-header/dealer-header.scss
  components/src/patterns/dealer-header/dealer-header.spec.ts
  components/src/patterns/dealer-header/dealer-header.tsx
  components/src/patterns/dealer-header/readme.md
  components/src/patterns/navigation/navigation.e2e.ts
  components/src/patterns/navigation/navigation.scss
  components/src/patterns/navigation/navigation.spec.ts
  components/src/patterns/navigation/navigation.tsx
  components/src/patterns/navigation/readme.md
  demo/react/package-lock.json
  demo/react/package.json
  package-lock.json
  package.json
  theme/core/colour/package-lock.json
  theme/core/colour/package.json
  theme/core/grid/package-lock.json
  theme/core/grid/package.json
  theme/core/icons/package-lock.json
  theme/core/icons/package.json
  theme/core/package-lock.json
  theme/core/package.json
  theme/core/typography/package-lock.json
  theme/core/typography/package.json
  theme/light/gulpfile.babel.js
  theme/light/package-lock.json
  theme/light/package.json
  theme/light/src/old/patterns/c-card.scss
  theme/light/src/old/patterns/c-content.scss
  theme/light/src/old/patterns/c-cookie.scss
  theme/light/src/old/patterns/c-modal.scss
  theme/light/src/old/patterns/c-navigation.scss
  theme/light/src/old/patterns/c-table.scss
Labels: Improvement, Theme, Component

#346 feat(table): sorting in data-table as web component
  .stylelintrc.json
  components/.storybook/preview.js
  components/package-lock.json
  components/src/components/table/readme.md
  components/src/components/table/table
  components/src/components/table/table-body-cell.tsx
  components/src/components/table/table-component.stories.js
  components/src/components/table/table-header-cell.tsx
  components/src/components/table/table.scss
  components/src/components/table/table.stories.js
  components/src/components/table/table.tsx
  components/src/components/theme/utilites.stories.js
  demo/HTML/package-lock.json
  demo/angular/angular11/package-lock.json
  demo/angular/angular12/package-lock.json
  demo/angular/angular12/src/app/components/home/home.component.html
  demo/angular/angular13/package-lock.json
  demo/angular/angular13/package.json
  demo/react/package-lock.json
  demo/vue/package-lock.json
  package-lock.json
  package.json
  theme/core/colour/package-lock.json
  theme/core/grid/package-lock.json
  theme/core/icons/package-lock.json
  theme/core/package-lock.json
  theme/core/typography/package-lock.json
  theme/light/package-lock.json
  theme/light/src/components/_table.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Component

#354 feat(dropdown): change selected option from outside
  components/package-lock.json
  components/package.json
  components/src/components/dropdown/dropdown-filter.tsx
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/dropdown.tsx
Labels: feature

#355 fix(data-table): post release improvements
  components/src/components/table/readme.md
  components/src/components/table/table.scss
  components/src/components/table/table.stories.js
  components/src/components/table/table.tsx
Labels: Improvement

#356 fix(modal): there is a issue setting overflow:hidden on body
  components/src/components/modal/modal.tsx
Labels: bug, Component

#361 chore: release sprint 30
  components/package-lock.json
  components/package.json
Labels: Improvement
