Repository scania-digital-design-system/sdds, pull requests merged in 2022-11, with the labels that each got.

#553 fix: set default text color in darkmode, and colors in storybook
  tegel/.storybook/ScaniaThemeDark.js
  tegel/.storybook/ScaniaThemeLight.js
  tegel/.storybook/assets/svg/ScaniaLogotype.svg
  tegel/.storybook/assets/svg/ScaniaLogotypeDarkMode.svg
  tegel/.storybook/manager.js
  tegel/.storybook/preview.js
  tegel/.storybook/scaniaThemeCommon.js
  theme/light/src/_reboot.scss
Labels: Theme

#539 feat(header): migrate header component
  package-lock.json
  package.json
  tegel/src/components/header/header-theme-vars.scss
  tegel/src/components/header/header.scss
  tegel/src/components/header/header.stories.js
  tegel/src/components/header/readme.md
  tegel/src/global/global.scss
  tegel/src/global/scania-fonts-vars.scss
Labels: Migration

#557 fix(textarea/textfield): handle-null-values-textfield/textarea
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/readme.md
  components/src/components/textfield/textfield.tsx
Labels: bug

#559 fix(textarea/textfield):textarea/field to handle null values for tegel
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.tsx
Labels: bug, Migration

#560 fix(textfield): display flex on sdds-helper to avoid clash between slot and char counter
  tegel/src/components/textfield/textfield.scss
Labels: bug, Migration

#561 fix(inline-tabs): make inline tabs html compliant
  components/src/components/tabs/inline-tabs/inline-tabs.stories.js
  components/src/components/tabs/inline-tabs/inline-tabs.tsx
Labels: bug

#548 fix(card): improve the story for the card component
  tegel/src/components/card/card.stories.ts
Labels: Improvement, Migration

#562 feat(colour): migrate colours story
  tegel/src/components/theme/colour/colour-brand.stories.js
  tegel/src/components/theme/colour/colour-scales.stories.js
  tegel/src/components/theme/colour/colour-semantic.stories.js
Labels: Migration

#564 feat(grid): migrate grid story
  tegel/src/components/theme/grid/grid.stories.js
Labels: Migration

#563 fix(banner): add sdds-icon instead of hard-coded SVGs, default value fix
  tegel/src/components/banner/banner.stories.ts
Labels: Improvement

#534 feat(tabs): migrate tabs components
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/readme.md
  tegel/src/components/tabs/inline-tabs/inline-tabs-theme-vars.scss
  tegel/src/components/tabs/inline-tabs/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs/inline-tabs.stories.ts
  tegel/src/components/tabs/inline-tabs/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs/readme.md
  tegel/src/components/tabs/navigation-tabs/navigation-tabs-theme-vars.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  tegel/src/components/tabs/navigation-tabs/readme.md
  tegel/src/global/global.scss
Labels: Migration

#566 feat(spacing): migrate spacing story
  tegel/src/components/theme/spacing/spacing-element.stories.ts
  tegel/src/components/theme/spacing/spacing-layout.stories.ts
Labels: Migration

#570 fix(code-sample): removal from components folder
  components/package.json
  components/src/components.d.ts
  components/src/components/code-sample/code-sample.scss
  components/src/components/code-sample/code-sample.tsx
  components/src/components/code-sample/readme.md
Labels: Improvement

#572 feat(typography): migrate typography stories
  tegel/package.json
  tegel/src/components/theme/typography/typography-body.stories.ts
  tegel/src/components/theme/typography/typography-detail.stories.ts
  tegel/src/components/theme/typography/typography-headline.stories.ts
  tegel/src/components/theme/typography/typography-paragraph.stories.ts
Labels: Migration

#575 fix(inline-tabs): corrected the use of aria/data-disabled
  components/src/components/tabs/inline-tabs/inline-tabs.tsx
Labels: bug

#576 fix(_core.scss): duplicate color variables generated
  theme/light/src/_core.scss
Labels: bug

#574 fix(inline-tabs): make inline-tabs valid html in tegel
  tegel/src/components/tabs/inline-tabs/inline-tabs.stories.ts
  tegel/src/components/tabs/inline-tabs/inline-tabs.tsx
Labels: bug, Migration

#569 feat(tooltips): migrating component
  tegel/src/components/tooltip/readme.md
  tegel/src/components/tooltip/tooltip-theme-vars.scss
  tegel/src/components/tooltip/tooltip.scss
  tegel/src/components/tooltip/tooltip.stories.js
  tegel/src/components/tooltip/tooltip.tsx
  tegel/src/global/global.scss
Labels: Migration

#546 fix(dropdown): dropdown label inside full height
  components/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/readme.md
Labels: bug

#583 fix(dropdown): multiselect dropdown doesnt show option labels
  tegel/src/components/dropdown/dropdown.tsx
Labels: bug

#582 fix(message): cleaned up and restructured the story for the message component
  tegel/src/components/message/message.stories.js
  tegel/src/components/message/message.stories.ts
Labels: Improvement, Migration

#571 fix(data-table): migration to tegel
  tegel/package-lock.json
  tegel/src/components/data-table/native-table.scss
  tegel/src/components/data-table/native-table.stories.ts
  tegel/src/components/data-table/table-body-cell/readme.md
  tegel/src/components/data-table/table-body-cell/table-body-cell.scss
  tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
  tegel/src/components/data-table/table-body-row-expandable/readme.md
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
  tegel/src/components/data-table/table-body-row/readme.md
  tegel/src/components/data-table/table-body-row/table-body-row.scss
  tegel/src/components/data-table/table-body-row/table-body-row.tsx
  tegel/src/components/data-table/table-body/readme.md
  tegel/src/components/data-table/table-body/table-body.scss
  tegel/src/components/data-table/table-body/table-body.tsx
  tegel/src/components/data-table/table-component-basic.stories.ts
  tegel/src/components/data-table/table-component-batch-actions.stories.ts
  tegel/src/components/data-table/table-component-custom-width.stories.ts
  tegel/src/components/data-table/table-component-event-listeners.stories.ts
  tegel/src/components/data-table/table-component-expandable-rows.stories.ts
  tegel/src/components/data-table/table-component-filtering.stories.ts
  tegel/src/components/data-table/table-component-multiselect.stories.ts
  tegel/src/components/data-table/table-component-pagination.stories.ts
  tegel/src/components/data-table/table-component-sorting.stories.ts
  tegel/src/components/data-table/table-footer/readme.md
  tegel/src/components/data-table/table-footer/table-footer.scss
  tegel/src/components/data-table/table-footer/table-footer.tsx
  tegel/src/components/data-table/table-header-cell/readme.md
  tegel/src/components/data-table/table-header-cell/table-header-cell.scss
  tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
  tegel/src/components/data-table/table-header/readme.md
  tegel/src/components/data-table/table-header/table-header.scss
  tegel/src/components/data-table/table-header/table-header.tsx
  tegel/src/components/data-table/table-toolbar/readme.md
  tegel/src/components/data-table/table-toolbar/table-toolbar.scss
  tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
  tegel/src/components/data-table/table/readme.md
  tegel/src/components/data-table/table/table.scss
  tegel/src/components/data-table/table/table.tsx
  tegel/src/global/global.scss
Labels: Migration

#586 fix/standardise storybook control option and default options
  tegel/src/components/accordion/accordion.stories.ts
  tegel/src/components/badges/badges.stories.ts
  tegel/src/components/banner/banner.stories.ts
  tegel/src/components/block/block.stories.ts
  tegel/src/components/button/button-native.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/button/button.scss
  tegel/src/components/card/card.stories.ts
  tegel/src/components/checkbox/checkbox.stories.ts
  tegel/src/components/chips/chips.stories.ts
  tegel/src/components/datetime/datetime.stories.ts
  tegel/src/components/divider/divider.stories.js
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.js
  tegel/src/components/dropdown/dropdown-native.stories.js
  tegel/src/components/dropdown/dropdown.stories.js
  tegel/src/components/header/header.stories.js
  tegel/src/components/icon/icon-font.stories.ts
  tegel/src/components/icon/icon-web-component.stories.ts
  tegel/src/components/link/link.stories.ts
  tegel/src/components/message/message.stories.ts
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.js
  tegel/src/components/popover-menu/popover-menu.stories.ts
  tegel/src/components/radio-button/radio-button.stories.js
  tegel/src/components/spinner/spinner.stories.js
  tegel/src/components/stepper/stepper.stories.js
  tegel/src/components/tabs/inline-tabs/inline-tabs.stories.ts
  tegel/src/components/textarea/textarea.stories.js
  tegel/src/components/textfield/textfield.stories.js
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.ts
  tegel/src/components/toggle/toggle.stories.ts
  tegel/src/components/tooltip/tooltip.stories.js
Labels: Migration

#598 fix(data-table): refactored how the top and subcomponents use enableMultiselect
  tegel/src/components/data-table/table-body-row/table-body-row.tsx
  tegel/src/components/data-table/table-body/table-body.tsx
  tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
  tegel/src/components/data-table/table-header/table-header.tsx
Labels: Improvement, Migration

#593 fix(data-table): standardise controls-values
  tegel/src/components/data-table/native-table.stories.ts
  tegel/src/components/data-table/table-component-basic.stories.ts
  tegel/src/components/data-table/table-component-batch-actions.stories.ts
  tegel/src/components/data-table/table-component-custom-width.stories.ts
  tegel/src/components/data-table/table-component-event-listeners.stories.ts
  tegel/src/components/data-table/table-component-expandable-rows.stories.ts
  tegel/src/components/data-table/table-component-filtering.stories.ts
  tegel/src/components/data-table/table-component-multiselect.stories.ts
  tegel/src/components/data-table/table-component-pagination.stories.ts
  tegel/src/components/data-table/table-component-sorting.stories.ts
Labels: Migration

#605 feat(storybook): google analytics addon
  tegel/.storybook/main.js
  tegel/.storybook/manager.js
  tegel/package-lock.json
  tegel/package.json
Labels: feature

#556 feat(side-menu) Migrating side menu
  tegel/src/components/side-menu/readme.md
  tegel/src/components/side-menu/side-menu-theme-vars.scss
  tegel/src/components/side-menu/side-menu.scss
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/global/global.scss
Labels: Migration

#600 fix/textfield state count issues - tegel
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.tsx
Labels: bug, Migration

#599 fix/textfield state count issues
  components/package-lock.json
  components/src/components/tabs/inline-tabs/inline-tabs.tsx
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/textfield.scss
  components/src/components/textfield/textfield.tsx
  sandbox/HTML/index.html
Labels: bug

#603 fix(popovercanvas/menu): added sdds-icon instead of SVG
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.ts
Labels: Improvement, Migration

#606 fix(file-extension): file extensions of stories files.
  tegel/src/components/divider/divider.stories.ts
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-native.stories.ts
  tegel/src/components/dropdown/dropdown.stories.ts
  tegel/src/components/radio-button/radio-button.stories.ts
  tegel/src/components/spinner/spinner.stories.ts
  tegel/src/components/stepper/stepper.stories.ts
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/theme/colour/colour-brand.stories.ts
  tegel/src/components/theme/colour/colour-scales.stories.ts
  tegel/src/components/theme/colour/colour-semantic.stories.ts
  tegel/src/components/theme/grid/grid.stories.ts
  tegel/src/components/tooltip/tooltip.stories.ts
Labels: Migration

#607 feat(storybook): adding Google Analytics without addon
  tegel/.storybook/main.js
  tegel/.storybook/manager-head.html
  tegel/.storybook/manager.js
Labels: Improvement

#612 fix(storybook): reverting hard coded values for GA due to Netlify error
  tegel/.storybook/manager-head.html
Labels: Improvement

#615 feat(storybook): adding Plausible
  tegel/.storybook/manager-head.html
Labels: Improvement

#604 fix(toast): added color to the wrapper class of the icon
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.ts
Labels: Improvement, Migration

#617 fix(dropdown): fix default select
  components/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/dropdown.tsx
Labels: bug

#618 fix(dropdown): reinstated ability to add custom click event listener
  components/package-lock.json
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/textfield.scss
  components/src/components/textfield/textfield.tsx
  tegel/src/components/dropdown/dropdown-option/dropdown-option.tsx
  tegel/src/components/dropdown/dropdown.tsx
Labels: bug

#624 feat(utility-classes): add utility classes to storybook
  tegel/src/components/utility/colour/background-color.stories.ts
  tegel/src/components/utility/colour/text-color.stories.ts
  tegel/src/components/utility/utility-classes/display.stories.mdx
  tegel/src/components/utility/utility-classes/float.stories.mdx
  tegel/src/components/utility/utility-classes/height.stories.mdx
  tegel/src/components/utility/utility-classes/margin.stories.mdx
  tegel/src/components/utility/utility-classes/opacity.stories.mdx
  tegel/src/components/utility/utility-classes/overflow.stories.mdx
  tegel/src/components/utility/utility-classes/padding.stories.mdx
  tegel/src/components/utility/utility-classes/placement.stories.mdx
  tegel/src/components/utility/utility-classes/position.stories.mdx
  tegel/src/components/utility/utility-classes/text-alignment.stories.mdx
  tegel/src/components/utility/utility-classes/visibility.stories.mdx
  tegel/src/components/utility/utility-classes/width.stories.mdx
  tegel/src/components/utility/utility-classes/z-index.stories.mdx
Labels: Migration

#626 docs(link): remove clsx package
  tegel/package-lock.json
  tegel/package.json
  tegel/src/components/link/link.stories.ts
Labels: Migration

#614 docs(side-menu): cleaned up the story and standardised the controls
  tegel/src/components/side-menu/side-menu.stories.ts
Labels: Improvement, Migration

#636 docs(storybook): removed storybook template files
  tegel/src/components/my-component/my-component.css
  tegel/src/components/my-component/my-component.e2e.ts
  tegel/src/components/my-component/my-component.spec.ts
  tegel/src/components/my-component/my-component.stories.ts
  tegel/src/components/my-component/my-component.tsx
  tegel/src/components/my-component/readme.md
  tegel/src/stories/Button.js
  tegel/src/stories/Button.stories.js
  tegel/src/stories/Header.js
  tegel/src/stories/Header.stories.js
  tegel/src/stories/Introduction.stories.mdx
  tegel/src/stories/Page.js
  tegel/src/stories/Page.stories.js
  tegel/src/stories/button.css
  tegel/src/stories/header.css
  tegel/src/stories/page.css
Labels: Migration

#631 fix(modal): standarise controls for modal
  tegel/src/components/modal/modal-native.stories.ts
  tegel/src/components/modal/modal-webcomponent.stories.ts
  tegel/src/components/modal/modal.stories.ts
Labels: Improvement, Migration

#635 fix(icon): dynamic import of scania/icons for icon-component
  components/src/components/icon/icon.tsx
Labels: bug

#637 docs(all): removes alphabetic sorting of controls.
  tegel/.storybook/preview.js
Labels: Improvement

#638 docs(tabs): removes the folder structure for the tabs stories
  tegel/src/components/tabs/inline-tabs-default/inline-tabs-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.ts
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs-default/readme.md
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
  tegel/src/global/global.scss
Labels: Improvement, Migration

#628 fix: adding not-allowed cursor to disabled state
  tegel/src/components/checkbox/checkbox.scss
  tegel/src/components/datetime/datetime.scss
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/radio-button/radio-button.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textfield/textfield.scss
Labels: Improvement

#639 fix/make all props camelCase
  tegel/src/components/badges/badges-component.tsx
  tegel/src/components/badges/readme.md
  tegel/src/components/button/button-component.tsx
  tegel/src/components/spinner/spinner.tsx
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/textfield/textfield.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: Improvement, Breaking, Migration

#633 fix(banner): close icon misplaced/shrinking when lots of text
  components/src/components/banner/banner.scss
  tegel/src/components/banner/banner.scss
  tegel/src/components/banner/banner.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: bug

#647 fix(badge): badge fixes
  tegel/.storybook/preview-head.html
  tegel/src/components/badge/badge.stories.ts
  tegel/src/components/badge/badges-component.tsx
  tegel/src/components/badge/badges.scss
  tegel/src/components/badge/readme.md
  tegel/src/components/badges/badges.stories.ts
Labels: Migration

#646 docs(data-table): adding storybook control for disablePadding prop in…
  tegel/src/components/data-table/table-body-cell/readme.md
  tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
  tegel/src/components/data-table/table-component-basic.stories.ts
Labels: Improvement

#644 fix(tooltip): added show on focus and removed bad lint naming
  tegel/src/components/tooltip/tooltip.stories.ts
  tegel/src/components/tooltip/tooltip.tsx
Labels: accessibility

#659 docs(canvas): made canvas the default tab
  tegel/.storybook/preview.js
Labels: Improvement

#661 fix(button): corrected the use of icons with xs button
  tegel/src/components/button/button-native.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
Labels: bug

#658 docs(foundations): hid the code by default for all stories under Foundations
  tegel/src/components/theme/colour/colour-brand.stories.ts
  tegel/src/components/theme/colour/colour-semantic.stories.ts
  tegel/src/components/theme/spacing/spacing-element.stories.ts
  tegel/src/components/theme/spacing/spacing-layout.stories.ts
  tegel/src/components/theme/typography/typography-headline.stories.ts
Labels: Improvement

#660 fix(side-menu): changed anchors to buttons for side-menu
  tegel/src/components/side-menu/side-menu.scss
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: Improvement

#651 fix(header): changed div/p as child of button to span
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: Improvement

#648 docs(dropdown-filter): adding missing controls
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
Labels: Improvement
