Repository scania-digital-design-system/sdds, pull requests merged in 2022-06, with the labels that each got.

#382 feat(table): actionbar section
  components/src/components/button/button.scss
  components/src/components/table/readme.md
  components/src/components/table/table-component.stories.js
  components/src/components/table/table.scss
  components/src/components/table/table.tsx
Labels: feature

#379 fix(dropdown): z-index, open/close + uuid
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.tsx
  demo/angular/angular12/package-lock.json
  demo/angular/angular12/package.json
  demo/angular/angular12/src/app/components/home/home.component.html
Labels: Improvement

#385 feat(storybook): adding Scania logotype
  components/.storybook/ScaniaTheme.js
  components/.storybook/assets/svg/ScaniaLogotype.svg
  components/.storybook/manager.js
  components/package-lock.json
  components/package.json
Labels: Improvement

#383 feat(table): pagination
  components/src/components/table/readme.md
  components/src/components/table/table-component.stories.js
  components/src/components/table/table.scss
  components/src/components/table/table.tsx
Labels: feature

#390 fix(storybook): removing fullpage example + header,footer,side-menu under component category
  components/src/components/footer/footer.scss
  components/src/components/footer/footer.stories.js
  components/src/components/footer/readme.md
  components/src/components/header/header.scss
  components/src/components/header/header.stories.js
  components/src/components/header/readme.md
  components/src/components/side-menu/readme.md
  components/src/components/side-menu/side-menu.scss
  components/src/components/side-menu/side-menu.stories.js
  components/src/components/theme/theme.scss
  components/src/patterns/fullpage/fullpage.stories.js
  components/src/patterns/readme.md
Labels: Improvement

#399 fix(button): remove display as flex
  components/src/components/button/button.scss
Labels: bug

#398 fix(table): reset search results if search query is empty
  components/src/components/table/table.tsx
Labels: bug

#384 feat: readonly prop for textfield & textarea
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.scss
  components/src/components/textarea/textarea.stories.js
  components/src/components/textarea/textarea.tsx
  components/src/components/textfield/readme.md
  components/src/components/textfield/textfield.scss
  components/src/components/textfield/textfield.stories.js
  components/src/components/textfield/textfield.tsx
Labels: feature
