Repository scania-digital-design-system/sdds, pull requests merged in 2022-01, with the labels that each got.

#255 Feature - Refactor scss structure in theme package
  theme/light/gulpfile.babel.js
  theme/light/src/_core.scss
  theme/light/src/_css-vars.scss
  theme/light/src/_reboot.scss
  theme/light/src/components/_button.scss
  theme/light/src/components/_dropdowns.scss
  theme/light/src/components/_footer.scss
  theme/light/src/components/_header.scss
  theme/light/src/components/_side-menu.scss
  theme/light/src/components/_tooltip.scss
  theme/light/src/old/_mixins.scss
  theme/light/src/old/components/_alert.scss
  theme/light/src/old/components/_button-group.scss
  theme/light/src/old/components/_custom-forms.scss
  theme/light/src/old/components/_forms.scss
  theme/light/src/old/components/_input-group.scss
  theme/light/src/old/components/_list-group.scss
  theme/light/src/old/components/_navs.scss
  theme/light/src/old/components/_pagination.scss
  theme/light/src/old/components/_progressbars.scss
  theme/light/src/old/core/old-colors.scss
  theme/light/src/old/patterns/c-card.scss
  theme/light/src/old/patterns/c-content.scss
  theme/light/src/old/patterns/c-cookie.scss
  theme/light/src/old/patterns/c-modal.scss
  theme/light/src/old/patterns/c-navigation.scss
  theme/light/src/old/patterns/c-table.scss
  theme/light/src/old/utilities/data-env.scss
  theme/light/src/old/utilities/global-style.css
  theme/light/src/old/utilities/loading.scss
  theme/light/src/old/utilities/typography.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Breaking, Theme, Component

#272 docs(readme): update readme for theme package, remove the cdn link
  theme/light/readme.md
Labels: Improvement

#269 feat(side menu): sticky collapse button and popover example fix
  components/src/patterns/side-menu/side-menu.scss
  components/src/patterns/side-menu/side-menu.stories.js
Labels: Bug, Improvement

#276 fix(copyright year): fixing copyright year
  LICENSE
  components/LICENSE
  components/src/components/theme/fullpage.stories.js
  components/src/patterns/footer/footer.stories.js
  demo/HTML/index.html
  demo/HTML/side-menu.html
  demo/angular/angular13/src/app/components/footer/footer.component.html
  demo/react/src/components/footer/Footer.js
Labels: Improvement

#275 feat(issue templates): update issue templates for bug, feature and question
  .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml
  .github/ISSUE_TEMPLATE/REQUEST_HELP.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: Feature

#280 fix(sdds-theme): fixing but related with text and background classes
  components/src/components/theme/utilites.stories.js
  theme/light/src/_core.scss
Labels: bug, Theme

#281 chore(bump versions): bump versions
  components/package-lock.json
  components/package.json
  theme/core/colour/package.json
  theme/core/grid/package.json
  theme/core/icons/package.json
  theme/core/typography/package.json
  theme/light/package-lock.json
  theme/light/package.json
Labels: bug

#283 chore(bump versions): bump versions
  components/package-lock.json
  components/package.json
  theme/core/colour/package.json
  theme/core/grid/package.json
  theme/core/icons/package.json
  theme/core/typography/package.json
  theme/light/package.json
Labels: bug

#285 feat(side menu): sticky collapse button in react demo
  components/src/patterns/side-menu/side-menu.scss
  components/src/patterns/side-menu/side-menu.stories.js
  demo/react/package-lock.json
  demo/react/package.json
  demo/react/src/components/sideMenu/SideMenu.js
  demo/react/src/index.js
  demo/react/src/index.scss
Labels: Improvement

#286 style(dropdown): restyling dropdown to fit along with other inputs
  components/src/components/dropdown/_dropdown-core.scss
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.tsx
  theme/light/src/components/_dropdowns.scss
Labels: Improvement

#271 refactor(header): decoupling and simplifying code
  components/.storybook/preview-body.html
  components/src/components/link/link.scss
  components/src/components/theme/theme.scss
  components/src/patterns/header/header.scss
  components/src/patterns/header/header.stories.js
  components/src/patterns/side-menu/_mixins.scss
  components/src/patterns/side-menu/_navbar-brand.scss
  components/src/patterns/side-menu/_navbar-collapsible.scss
  components/src/patterns/side-menu/_navbar-menu-item.scss
  components/src/patterns/side-menu/_navbar-toolbar-menu.scss
  components/src/patterns/side-menu/side-menu.scss
  components/src/patterns/side-menu/side-menu.stories.js
  package-lock.json
  theme/light/src/components/_header.scss
  theme/light/src/components/_side-menu.scss
  theme/light/src/theme/sdds-theme.scss
Labels: Improvement

#288 fix(side-menu): side menu dropdown item opened border fix
  components/src/components/dropdown/dropdown.scss
  components/src/patterns/side-menu/side-menu.scss
Labels: bug

#294 Update FEATURE_REQUEST.yaml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml
Labels: feature, Improvement
