Repository scania-digital-design-system/sdds, pull requests merged in 2022-12, with the labels that each got.

#670 feat(): add design and a11y addons to sb
  components/package-lock.json
  package-lock.json
  package.json
  tegel/.storybook/main.js
  tegel/src/components/accordion/accordion.stories.ts
  tegel/src/components/badge/badge.stories.ts
  tegel/src/components/banner/banner.stories.ts
  tegel/src/components/block/block.stories.ts
  tegel/src/components/breadcrumb/breadcrumb.stories.ts
  tegel/src/components/button/button-native.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/card/card.stories.ts
  tegel/src/components/checkbox/checkbox.stories.ts
  tegel/src/components/chips/chips.stories.ts
  tegel/src/components/datetime/datetime.stories.ts
  tegel/src/components/divider/divider.stories.ts
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-native.stories.ts
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
  tegel/src/components/footer/footer.stories.ts
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-default.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
  tegel/src/components/icon/icon-font.stories.ts
  tegel/src/components/icon/icon-web-component.stories.ts
  tegel/src/components/link/link.stories.ts
  tegel/src/components/message/message.stories.ts
  tegel/src/components/modal/modal-native.stories.ts
  tegel/src/components/modal/modal-webcomponent.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.ts
  tegel/src/components/radio-button/radio-button.stories.ts
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/components/slider/slider.stories.ts
  tegel/src/components/spinner/spinner.stories.ts
  tegel/src/components/stepper/stepper.stories.ts
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.ts
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/toast/toast.stories.ts
  tegel/src/components/toggle/toggle.stories.ts
  tegel/src/components/tooltip/tooltip.stories.ts
Labels: 🚧 migration

#657 fix/toast dismiss button
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement

#673 fix(textarea): refactored css so width styles is used for all states
  tegel/src/components/textarea/textarea.scss
Labels: 🪲 bug, 🚧 migration

#679 fix(textarea): changed readonly and autofocus props to camelCase
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#680 fix(textarea/textfield): changed default value from null to empty string
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.tsx
Labels: 🚀 improvement

#682 fix(toggle): added disable prop to native input element
  tegel/src/components/toggle/toggle.stories.ts
Labels: 🚀 improvement

#683 fix(block): changed the class names for block to conform with convention
  tegel/src/components/block/block.scss
  tegel/src/components/block/block.stories.ts
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#685 fix(navigation-tabs): changed the class names for navigation-tabs to conform with convention
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#672 feat(dropdown): add openDirection prop
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
  tegel/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/readme.md
Labels: 🚀 improvement

#696 fix(accordion): padding and chevron fixes
  tegel/src/components/accordion/accordion-item/accordion-item.tsx
  tegel/src/components/accordion/accordion-item/readme.md
  tegel/src/components/accordion/accordion.scss
  tegel/src/components/icon/readme.md
Labels: 🚀 improvement

#690 fix: capital letters to story names
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/side-menu/side-menu.stories.ts
Labels: 🚀 improvement

#695 feat(textfield): added color to suffix/prefix icons
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.tsx
Labels: 🚀 improvement

#692 feat(modal): added 16px gap between buttons on modal
  tegel/src/components/modal/modal.scss
Labels: 🚀 improvement

#676 fix(textarea/textfield): label position label props
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/textfield/textfield.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#677 fix(textfield): changed the nominwidth prop to noMinWidth
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/textfield/textfield.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#693 fix(badge): replace size prop value default with large
  tegel/src/components/badge/badge.stories.ts
  tegel/src/components/badge/badges.scss
  tegel/src/components/badge/badges.tsx
  tegel/src/components/badge/readme.md
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚧 migration

#691 fix(tegel): remove base value and use px instead of rem
  tegel/package-lock.json
  tegel/package.json
  tegel/src/components/banner/banner.scss
  tegel/src/components/breadcrumb/breadcrumb.scss
  tegel/src/components/button/button.scss
  tegel/src/components/card/card.scss
  tegel/src/components/checkbox/checkbox.scss
  tegel/src/components/datetime/datetime.scss
  tegel/src/components/dropdown/_dropdown-core.scss
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/dropdown/dropdown.scss
  tegel/src/components/modal/modal.scss
  tegel/src/components/radio-button/radio-button.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/theme/grid/grid.stories.ts
  tegel/src/components/theme/spacing/spacing-element.stories.ts
  tegel/src/components/theme/spacing/spacing-layout.stories.ts
  tegel/src/components/theme/typography/typography-body.stories.ts
  tegel/src/components/theme/typography/typography-detail.stories.ts
  tegel/src/components/theme/typography/typography-headline.stories.ts
  tegel/src/components/theme/typography/typography-paragraph.stories.ts
  tegel/src/components/toast/toast.scss
  tegel/src/components/toggle/toggle.scss
  tegel/src/components/tooltip/tooltip.scss
  tegel/src/global/global.scss
  tegel/src/stories/Migration/Migration.stories.mdx
  theme/core/spacing/_vars.scss
  theme/core/spacing/spacing-vars.scss
  theme/core/typography/_mixins.scss
  theme/core/typography/_vars.scss
  theme/core/typography/typography-vars.scss
Labels: 🚀 improvement, 🚨 breaking, 🚧 migration

#694 docs: add a readme for the tegel package
  tegel/readme.md
Labels: 📚 docs

#669 fix(dropdown): label placement and padding
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/dropdown/dropdown.scss
  tegel/src/components/dropdown/dropdown.tsx
Labels: 🪲 bug, 🚀 improvement

#701 fix(accordion): css rules for accordion
  components/src/components/accordion/accordion.scss
Labels: 🪲 bug

#689 feat(dropdown-option): adding disabled state
  components/src/components.d.ts
  components/src/components/dropdown/dropdown-option.tsx
  components/src/components/dropdown/dropdown.scss
  components/src/components/dropdown/dropdown.stories.js
  components/src/components/dropdown/readme.md
  tegel/src/components/badge/badge.stories.ts
  tegel/src/components/dropdown/dropdown-option/dropdown-option.tsx
  tegel/src/components/dropdown/dropdown-option/readme.md
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
  tegel/src/components/dropdown/dropdown.scss
Labels: 🆕 feature, 🧑‍🎨 design

#707 fix: removing Google Analytics from storybook
  tegel/.storybook/manager-head.html
Labels: 🚀 improvement

#687 feat(inline-tabs/inline-tabs-fullbleed): added variant prop
  components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.js
  components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  components/src/components/tabs/inline-tabs-fullbleed/readme.md
  components/src/components/tabs/inline-tabs/inline-tabs.scss
  components/src/components/tabs/inline-tabs/inline-tabs.stories.js
  components/src/components/tabs/inline-tabs/inline-tabs.tsx
  components/src/components/tabs/inline-tabs/readme.md
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.ts
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs-default/readme.md
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/readme.md
Labels: 🪲 bug

#704 fix(chips): added font-size for icon in component css
  tegel/src/components/chips/chips.scss
  tegel/src/components/chips/chips.stories.ts
Labels: 🚀 improvement, 🚧 migration

#705 docs(header): removed controls since js make demo interactive
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-default.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
Labels: 🚀 improvement, 📚 docs

#706 fix(data-table): native component caption fixes
  tegel/src/components/data-table/native-table.scss
Labels: 🚀 improvement

#708 docs: add tegel storybook favicons
  tegel/.storybook/main.js
  tegel/.storybook/manager-head.html
  tegel/package.json
  tegel/public/android-chrome-192x192.png
  tegel/public/android-chrome-512x512.png
  tegel/public/apple-touch-icon.png
  tegel/public/favicon-16x16.png
  tegel/public/favicon-32x32.png
  tegel/public/favicon.ico
  tegel/public/site.webmanifest
  tegel/src/components/tabs/inline-tabs-default/readme.md
  tegel/src/components/tabs/inline-tabs-fullbleed/readme.md
Labels: 📚 docs

#702 docs(): add comments to demo wrappers in storybook
  tegel/src/components/button/button-native.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/card/card.stories.ts
  tegel/src/components/divider/divider.stories.ts
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-native.stories.ts
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-default.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
  tegel/src/components/modal/modal-native.stories.ts
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.ts
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/components/slider/slider.stories.ts
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/tooltip/tooltip.stories.ts
Labels: 📚 docs

#703 feat(accordion-item): styling and refactoring
  tegel/src/components/accordion/accordion-item/accordion-item.scss
  tegel/src/components/accordion/accordion-item/accordion-item.tsx
  tegel/src/components/accordion/accordion-theme-vars.scss
  tegel/src/components/accordion/accordion.scss
  tegel/src/components/accordion/accordion.stories.ts
  tegel/src/components/accordion/accordion.tsx
  tegel/src/components/accordion/readme.md
  tegel/src/mixins/_disabled-style.scss
  tegel/src/mixins/mixins.scss
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🆕 feature, 🚀 improvement, 🚨 breaking

#709 docs(data-table): added default value for multiselect
  tegel/src/components/data-table/table-component-multiselect.stories.ts
Labels: 📚 docs

#711 feat(typography): removed dep on scania/typography
  tegel/src/global/global.scss
  tegel/src/global/scania-fonts-selectors.scss
Labels: 🚀 improvement, 🔡 typography

#700 feat(modal): refactored how we open the modal and removed prop selector
  tegel/src/components/modal/modal-webcomponent.stories.ts
  tegel/src/components/modal/modal.tsx
  tegel/src/components/modal/readme.md
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking, 🚧 migration

#712 fix(foundation-stories): code formatting and examples improvements
  tegel/src/components/icon/icon-font.stories.ts
  tegel/src/components/theme/typography/typography-body.stories.ts
  tegel/src/components/theme/typography/typography-detail.stories.ts
  tegel/src/components/theme/typography/typography-paragraph.stories.ts
  tegel/src/foundations-stories/colour/colour-brand.stories.ts
  tegel/src/foundations-stories/colour/colour-scales.stories.ts
  tegel/src/foundations-stories/colour/colour-semantic.stories.ts
  tegel/src/foundations-stories/grid/grid.stories.ts
  tegel/src/foundations-stories/spacing/spacing-element.stories.ts
  tegel/src/foundations-stories/spacing/spacing-layout.stories.ts
  tegel/src/foundations-stories/typography/typography-body.stories.ts
  tegel/src/foundations-stories/typography/typography-detail.stories.ts
  tegel/src/foundations-stories/typography/typography-headline.stories.ts
  tegel/src/foundations-stories/typography/typography-paragraph.stories.ts
Labels: 🚀 improvement

#715 fix(accordion): added bottom border to last child
  tegel/src/components/accordion/accordion.scss
Labels: 🪲 bug

#714 fix(sdds-icon): removed all selfclosures
  tegel/src/components/banner/banner.stories.ts
  tegel/src/components/data-table/table-body/table-body.tsx
  tegel/src/components/data-table/table-component-batch-actions.stories.ts
  tegel/src/components/footer/footer.stories.ts
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
  tegel/src/components/icon/icon-web-component.stories.ts
  tegel/src/components/message/message.stories.ts
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.ts
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/components/stepper/stepper.stories.ts
  tegel/src/components/textfield/textfield.stories.ts
Labels: 🚀 improvement

#716 fix: component stories improvements
  tegel/src/components/accordion/accordion.stories.ts
  tegel/src/components/block/block-theme-vars.scss
  tegel/src/components/block/block.scss
  tegel/src/components/block/block.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/card/card.stories.ts
  tegel/src/components/chips/chips.stories.ts
  tegel/src/components/datetime/datetime.stories.ts
  tegel/src/components/datetime/datetime.tsx
  tegel/src/components/datetime/readme.md
  tegel/src/components/divider/divider.stories.ts
  tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
  tegel/src/components/dropdown/dropdown-native.stories.ts
  tegel/src/components/dropdown/dropdown-wc-default.stories.ts
  tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
  tegel/src/components/header/header-all.stories.ts
  tegel/src/components/header/header-default.stories.ts
  tegel/src/components/header/header-inline.stories.ts
  tegel/src/components/header/header-search.stories.ts
  tegel/src/components/header/header-toolbar.stories.ts
  tegel/src/components/message/message.scss
  tegel/src/components/message/message.stories.ts
  tegel/src/components/modal/modal-native.stories.ts
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-menu/popover-menu-icons.stories.ts
  tegel/src/components/popover-menu/popover-menu.stories.ts
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/components/stepper/stepper.scss
  tegel/src/components/stepper/stepper.stories.ts
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.stories.ts
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.stories.ts
  tegel/src/components/textfield/textfield.tsx
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.ts
  tegel/src/components/tooltip/tooltip.stories.ts
  tegel/src/global/global.scss
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement

#718 fix(button): corrected the margin left for button icon
  tegel/src/components/button/button.scss
Labels: 🪲 bug, 🚧 migration

#717 fix: box sizing mixin
  tegel/src/components/accordion/accordion-item/accordion-item.scss
  tegel/src/components/accordion/accordion.scss
  tegel/src/components/badge/badges.scss
  tegel/src/components/banner/banner.scss
  tegel/src/components/block/block.scss
  tegel/src/components/breadcrumb/breadcrumb.scss
  tegel/src/components/button/button.scss
  tegel/src/components/card/card.scss
  tegel/src/components/checkbox/checkbox.scss
  tegel/src/components/chips/chips.scss
  tegel/src/components/data-table/native-table.scss
  tegel/src/components/data-table/table-body-cell/table-body-cell.scss
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss
  tegel/src/components/data-table/table-body-row/table-body-row.scss
  tegel/src/components/data-table/table-body/table-body.scss
  tegel/src/components/data-table/table-footer/table-footer.scss
  tegel/src/components/data-table/table-header-cell/table-header-cell.scss
  tegel/src/components/data-table/table-header/table-header.scss
  tegel/src/components/data-table/table-toolbar/table-toolbar.scss
  tegel/src/components/data-table/table/table.scss
  tegel/src/components/datetime/datetime.scss
  tegel/src/components/divider/divider.scss
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/dropdown/dropdown.scss
  tegel/src/components/footer/footer-theme-vars.scss
  tegel/src/components/footer/footer.scss
  tegel/src/components/footer/footer.stories.ts
  tegel/src/components/header/header.scss
  tegel/src/components/link/link.scss
  tegel/src/components/message/message.scss
  tegel/src/components/modal/modal.scss
  tegel/src/components/popover-canvas/popover-canvas.scss
  tegel/src/components/popover-menu/popover-menu-item.scss
  tegel/src/components/popover-menu/popover-menu.scss
  tegel/src/components/radio-button/radio-button.scss
  tegel/src/components/side-menu/side-menu.scss
  tegel/src/components/side-menu/side-menu.stories.ts
  tegel/src/components/slider/slider.scss
  tegel/src/components/spinner/spinner.scss
  tegel/src/components/stepper/stepper.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/toast/toast.scss
  tegel/src/components/toggle/toggle.scss
  tegel/src/components/tooltip/tooltip.scss
  tegel/src/mixins/_box-sizing.scss
  tegel/src/mixins/mixins.scss
Labels: 🚀 improvement

#722 fix(): Change "Webcomponent" to "Web Component" in relevant components
  tegel/src/components/button/button-native.stories.ts
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/chips/chips.stories.ts
  tegel/src/components/message/message.stories.ts
  tegel/src/components/modal/modal.scss
  tegel/src/components/popover-menu/popover-menu-item.scss
  tegel/src/components/stepper/stepper.scss
  tegel/src/components/stepper/stepper.stories.ts
  tegel/src/components/toast/toast.stories.ts
Labels: 🚧 migration

#725 fix(): Change "Webcomponent" to "Web Component" in args for affected …
  tegel/src/components/button/button-webcomponent.stories.ts
  tegel/src/components/message/message.stories.ts
  tegel/src/components/toast/toast.stories.ts
Labels: 🚧 migration

#726 docs(welcome-page): removed placeholder text
  tegel/src/stories/IntroductionTegel.stories.mdx
Labels: 📚 docs

#727 build(tegel): committing correct stencil -v, igoring stories on build
  tegel/package-lock.json
  tegel/package.json
  tegel/readme.md
  tegel/stencil.config.ts
  tegel/tsconfig.json
Labels: 👷🏻 build👷🏻‍♀️

#713 feat: rename close btn classes
  tegel/src/components/modal/modal-native.stories.ts
  tegel/src/components/modal/modal.scss
  tegel/src/components/modal/modal.tsx
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.ts
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking, 🔧 component

#719 feat z-index
  tegel/.storybook/preview.css
  tegel/.storybook/preview.js
  tegel/src/components/accordion/accordion.scss
  tegel/src/components/dropdown/_dropdown-core.scss
  tegel/src/components/dropdown/dropdown.scss
  tegel/src/components/footer/footer.scss
  tegel/src/components/header/header.scss
  tegel/src/components/modal/modal.scss
  tegel/src/components/popover-canvas/popover-canvas.scss
  tegel/src/components/popover-menu/popover-menu.scss
  tegel/src/components/slider/slider.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/tooltip/tooltip.scss
  tegel/src/mixins/_z-index.scss
Labels: 🚨 breaking, 🔧 component

#733 fix(modal): removed stopPropogation on modal click
  components/src/components/modal/modal.tsx
Labels: 🪲 bug, 📦 @scania/components

#731 feat: rewrite native table css to classes are not needed
  tegel/src/components/data-table/native-table.scss
  tegel/src/components/data-table/native-table.stories.ts
Labels: 🆕 feature, 🚀 improvement, 🔧 component
