Repository scania-digital-design-system/sdds, pull requests merged in 2022-10, with the labels that each got.

#476 chore: disabled eslint prefer-default-export rule
  .eslintrc.json
Labels: Improvement

#477 fix(dropdown): changed the dropdown options to use the bg variables
  components/src/components/dropdown/_dropdown-core.scss
  components/src/components/dropdown/dropdown.scss
Labels: bug

#480 fix(header): fix position of active item indicator when its on an inline menu
  components/src/components/header/header.scss
Labels: bug

#481 fix(dropdown): fix misplaced native dropdown label
  components/src/components/dropdown/dropdown-select.scss
Labels: bug

#484 fix(header): stop dropdowns showing briefly on page load
  components/src/components/header/header.scss
Labels: bug

#483 fix(banner): changed the padding/margin of the close-btn and icon to …
  components/src/components/banner/banner.scss
  components/src/components/banner/banner.stories.js
Labels: bug, Design

#485 fix(dropdown): place outside label 8px above dropdown like design spec
  components/src/components/dropdown/_dropdown-core.scss
  components/src/components/dropdown/dropdown.scss
Labels: bug, Design

#420 refactor(data-table): separation in sub-components, expandable rows feature
  components/src/components/data-table/native-table.scss
  components/src/components/data-table/native-table.stories.js
  components/src/components/data-table/table-body-cell/readme.md
  components/src/components/data-table/table-body-cell/table-body-cell.scss
  components/src/components/data-table/table-body-cell/table-body-cell.tsx
  components/src/components/data-table/table-body-row-expandable/readme.md
  components/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss
  components/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
  components/src/components/data-table/table-body-row/readme.md
  components/src/components/data-table/table-body-row/table-body-row.scss
  components/src/components/data-table/table-body-row/table-body-row.tsx
  components/src/components/data-table/table-body/readme.md
  components/src/components/data-table/table-body/table-body.scss
  components/src/components/data-table/table-body/table-body.tsx
  components/src/components/data-table/table-component-basic.stories.js
  components/src/components/data-table/table-component-batch-actions.stories.js
  components/src/components/data-table/table-component-custom-width.stories.js
  components/src/components/data-table/table-component-disabled-functionalities.stories.js
  components/src/components/data-table/table-component-expandable-rows.stories.js
  components/src/components/data-table/table-component-filtering.stories.js
  components/src/components/data-table/table-component-multiselect.stories.js
  components/src/components/data-table/table-component-pagination.stories.js
  components/src/components/data-table/table-component-sorting.stories.js
  components/src/components/data-table/table-footer/readme.md
  components/src/components/data-table/table-footer/table-footer.scss
  components/src/components/data-table/table-footer/table-footer.tsx
  components/src/components/data-table/table-header-cell/readme.md
  components/src/components/data-table/table-header-cell/table-header-cell.scss
  components/src/components/data-table/table-header-cell/table-header-cell.tsx
  components/src/components/data-table/table-header/readme.md
  components/src/components/data-table/table-header/table-header.scss
  components/src/components/data-table/table-header/table-header.tsx
  components/src/components/data-table/table-toolbar/readme.md
  components/src/components/data-table/table-toolbar/table-toolbar.scss
  components/src/components/data-table/table-toolbar/table-toolbar.tsx
  components/src/components/data-table/table/readme.md
  components/src/components/data-table/table/table.scss
  components/src/components/data-table/table/table.tsx
  components/src/components/table/readme.md
  components/src/components/table/table-body-cell.tsx
  components/src/components/table/table-body-row.tsx
  components/src/components/table/table-body.tsx
  components/src/components/table/table-component.stories.js
  components/src/components/table/table-footer.tsx
  components/src/components/table/table-header-row.tsx
  components/src/components/table/table-header.tsx
  components/src/components/table/table-toolbar.tsx
  components/src/components/table/table.scss
  components/src/components/table/table.stories.js
  components/src/components/table/table.tsx
  components/src/components/theme/theme.scss
  components/src/helpers/components-shared.scss
  package-lock.json
  package.json
Labels: Improvement

#514 feat(accordion): migrate accordion component
  components/src/components.d.ts
  components/src/components/accordion/accordion-item.tsx
  components/src/components/accordion/accordion-theme-vars.scss
  components/src/components/accordion/accordion.scss
  components/src/components/accordion/accordion.spec.ts
  components/src/components/accordion/accordion.stories.ts
  components/src/components/accordion/accordion.tsx
  components/src/components/accordion/readme.md
  components/src/global/global.scss
Labels: migration

#511 feat(toggle): migrate toggle component
  components/src/components/toggle/toggle-theme-vars.scss
  components/src/components/toggle/toggle.scss
  components/src/components/toggle/toggle.stories.ts
  components/src/global/global.scss
Labels: migration

#505 feat(datetime): migrate datetime component
  components/npm
  components/src/components.d.ts
  components/src/components/datetime/datetime-theme-vars.scss
  components/src/components/datetime/datetime.scss
  components/src/components/datetime/datetime.stories.ts
  components/src/components/datetime/datetime.tsx
  components/src/components/datetime/readme.md
  components/src/global/global.scss
  npm
  sandbox/HTML/.prettierignore
  sandbox/HTML/index.html
Labels: migration

#492 feat:(checkbox) migrate checkbox component
  components/src/components/checkbox/checkbox-theme-vars.scss
  components/src/components/checkbox/checkbox.scss
  components/src/components/checkbox/checkbox.stories.ts
  components/src/global/global.scss
Labels: migration

#501 feat(message): migrate message component
  components/src/components/message/message-theme-vars.scss
  components/src/components/message/message.scss
  components/src/components/message/message.stories.js
  components/src/global/global.scss
Labels: migration

#512 feat(card): migrate card component
  components/src/components.d.ts
  components/src/components/card/card-theme-vars.scss
  components/src/components/card/card.scss
  components/src/components/card/card.stories.js
  components/src/components/card/card.tsx
  components/src/components/card/readme.md
  components/src/global/global.scss
  components/src/global/scania-fonts-vars.scss
  components/src/stories/assets/image/card-img-left.png
  components/src/stories/assets/image/card-img.png
Labels: migration

#513 fix(divider): migration of the divider component
  components/src/components/divider/divider-theme-vars.scss
  components/src/components/divider/divider.scss
  components/src/components/divider/divider.stories.js
  components/src/global/global.scss
Labels: migration

#515 feat(stepper): migrate stepper component
  components/src/components/stepper/stepper-theme-vars.scss
  components/src/components/stepper/stepper.scss
  components/src/components/stepper/stepper.stories.js
  components/src/global/global.scss
Labels: migration

#499 feat(block): Migrate block
  components-old/package-lock.json
  components/package-lock.json
  components/src/components.d.ts
  components/src/components/banner/banner.scss
  components/src/components/block/block-theme-vars.scss
  components/src/components/block/block.scss
  components/src/components/block/block.stories.ts
  components/src/global/global.scss
  package-lock.json
  theme/core/colour/package-lock.json
  theme/core/grid/package-lock.json
  theme/core/icons/package-lock.json
  theme/core/package-lock.json
  theme/core/typography/package-lock.json
  theme/light/package-lock.json
Labels: migration

#502 feat(toast): migrate toast
  components-old/package-lock.json
  components/package-lock.json
  components/package.json
  components/src/components/banner/banner.scss
  components/src/components/toast/toast-theme-vars.scss
  components/src/components/toast/toast.scss
  components/src/components/toast/toast.stories.js
  components/src/global/global.scss
  package-lock.json
  theme/core/typography/_tokens.scss
Labels: migration

#527 fix: checkbox story cleanup + eslint rule for import resolution
  tegel/.eslintrc.json
  tegel/src/components/checkbox/checkbox.stories.ts
Labels: migration

#532 fix(global.d.ts): add a type for .md files so it can be imported
  tegel/.gitignore
  tegel/src/global.d.ts
Labels: bug

#529 feat(popover-menu): migrate popover-menu component
  tegel/package.json
  tegel/src/components/popover-menu/documentation.txt
  tegel/src/components/popover-menu/popover-menu-item.scss
  tegel/src/components/popover-menu/popover-menu-theme-vars.scss
  tegel/src/components/popover-menu/popover-menu.scss
  tegel/src/components/popover-menu/popover-menu.stories.js
  tegel/src/components/popover-menu/popover-menu.tsx
  tegel/src/components/popover-menu/readme.md
  tegel/src/global/global.scss
Labels: migration

#528 feat(popover-canvas): migrate popover-canvas component
  tegel/src/components/popover-canvas/documentation.txt
  tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss
  tegel/src/components/popover-canvas/popover-canvas.scss
  tegel/src/components/popover-canvas/popover-canvas.stories.ts
  tegel/src/components/popover-canvas/popover-canvas.tsx
  tegel/src/components/popover-canvas/readme.md
  tegel/src/global/global.scss
Labels: migration

#530 feat(textarea/textfield): migrate textarea textfield component
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea-theme-vars.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textarea/textarea.stories.js
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield-theme-vars.scss
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.stories.js
  tegel/src/components/textfield/textfield.tsx
Labels: migration

#540 fix(icon): migration
  icons/gulpfile.js
  tegel/package-lock.json
  tegel/src/components/icon/icon-font.stories.ts
  tegel/src/components/icon/icon-web-component.stories.ts
  tegel/src/components/icon/icon.scss
  tegel/src/components/icon/icon.tsx
  tegel/src/components/icon/iconsArray.js
  tegel/src/components/icon/readme.md
Labels: migration

#533 feat(footer): migrate footer component
  tegel/src/components/footer/footer-theme-vars.scss
  tegel/src/components/footer/footer.scss
  tegel/src/components/footer/footer.stories.ts
  tegel/src/components/footer/readme.md
  tegel/src/global/global.scss
Labels: migration

#536 feat: adding more details to tegel package.json
  tegel/package-lock.json
  tegel/package.json
Labels: Improvement, Migration

#538 fix(card): removing unused web component files
  tegel/src/components/card/card.tsx
  tegel/src/components/card/readme.md
Labels: Migration

#552 fix: various storybook improvements
  tegel/.storybook/ScaniaTheme.js
  tegel/.storybook/assets/svg/ScaniaLogotype.svg
  tegel/.storybook/manager-head.html
  tegel/.storybook/manager.js
  tegel/.storybook/preview.js
  tegel/package-lock.json
  tegel/package.json
  tegel/src/components/badges/badges.stories.ts
  tegel/src/components/card/card.stories.ts
  tegel/src/components/chips/chips.stories.ts
  tegel/src/components/datetime/datetime.stories.ts
  tegel/src/components/footer/footer.stories.ts
  tegel/src/components/link/link.stories.ts
  tegel/src/components/toast/toast.stories.ts
  tegel/src/components/toggle/toggle.stories.ts
  tegel/src/components/website-components/code-sample/code-sample.scss
  tegel/src/components/website-components/code-sample/code-sample.tsx
  tegel/src/global.d.ts
  tegel/src/stories/IntroductionTegel.stories.mdx
  theme/light/src/_reboot.scss
Labels: Improvement, Migration

#543 fix(textfield): display flex on sdds-helper to avoid clash between slot and char counter
  components/src/components/textfield/textfield.scss
Labels: bug

#549 fix(textarea/textfield): refine the number of stories
  tegel/src/components/textarea/textarea.stories.js
  tegel/src/components/textfield/textfield.stories.js
Labels: Improvement, Migration

#554 fix: adding utility classes and mixins to Tegel
  tegel/src/global/_utility-classes.scss
  tegel/src/global/global.scss
  tegel/src/mixins/_flex-center.scss
  tegel/src/mixins/_focus-state.scss
  tegel/src/mixins/_scrollbar.scss
  tegel/src/mixins/_shake-animation.scss
  tegel/src/mixins/mixins.scss
  tegel/src/mixins/readme.md
Labels: Migration
