Repository scania-digital-design-system/sdds, pull requests merged in 2023-01, with the labels that each got.

#738 feat(beta.11): bumped npm version for release 0.0.1-beta.11
  tegel/package-lock.json
  tegel/package.json
Labels: 🎉 release

#720 fix(date-time): align props date time and introduce default-value
  tegel/src/components/datetime/datetime.scss
  tegel/src/components/datetime/datetime.stories.ts
  tegel/src/components/datetime/datetime.tsx
  tegel/src/components/datetime/readme.md
  tegel/src/components/icon/readme.md
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking

#766 docs(bug-report): text corrections
  .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
Labels: 📚 docs

#758 fix(modal): fix the constant overflow on modal
  components/src/components/modal/_modal-core.scss
  components/src/components/modal/modal.tsx
Labels: 🪲 bug, 📦 @scania/components

#730 feat(breadcrumb): webcomponent
  tegel/src/components/breadcrumb/breadcrumb-component.scss
  tegel/src/components/breadcrumb/breadcrumb-component.stories.ts
  tegel/src/components/breadcrumb/breadcrumb-item/breadcrumb-item.scss
  tegel/src/components/breadcrumb/breadcrumb-item/breadcrumb-item.tsx
  tegel/src/components/breadcrumb/breadcrumb-item/readme.md
  tegel/src/components/breadcrumb/breadcrumb.stories.tsx
  tegel/src/components/breadcrumb/breadcrumb.tsx
  tegel/src/components/breadcrumb/readme.md
Labels: 🆕 feature, 🔧 component

#771 fix(datetime): added correct type values for stories
  tegel/src/components/datetime/datetime.stories.tsx
Labels: 🪲 bug

#768 docs: fix radio storybook example
  tegel/src/components/radio-button/radio-button.stories.tsx
Labels: 🚀 improvement, 📚 docs

#769 fix: popover storybook code example
  tegel/src/components/popover-canvas/popover-canvas.stories.tsx
  tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
  tegel/src/components/popover-menu/popover-menu.stories.tsx
Labels: 🚀 improvement, 📚 docs

#770 docs(button): hide text control in "only icon" stories
  tegel/src/components/button/button-native.stories.tsx
  tegel/src/components/button/button-webcomponent.stories.tsx
Labels: 📚 docs

#776 fix: popover canvas color
  tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss
Labels: 🪲 bug

#777 fix: popover position
  tegel/src/components/popover-canvas/popover-canvas.scss
  tegel/src/components/popover-canvas/popover-canvas.stories.tsx
  tegel/src/components/popover-canvas/popover-canvas.tsx
  tegel/src/components/popover-menu/popover-menu.tsx
Labels: 🪲 bug, 🚀 improvement

#743 fix(divider): add dark mode variables
  tegel/src/components/divider/divider-theme-vars.scss
  tegel/src/components/divider/divider.scss
  tegel/src/components/divider/divider.stories.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: :dark_sunglasses: Mode

#753 fix(textarea): add dark mode variables
  tegel/src/components/textarea/textarea-theme-vars.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textarea/textarea.stories.tsx
  tegel/src/components/textarea/textarea.tsx
Labels: :dark_sunglasses: Mode

#779 fix(modal): fix body text spacing
  tegel/src/components/modal/modal-native.stories.tsx
  tegel/src/components/modal/modal-webcomponent.stories.tsx
  tegel/src/components/modal/modal.scss
Labels: 🔧 component

#752 fix(tabs): add dark mode variables
  tegel/src/components/tabs/inline-tabs-default/inline-tabs-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  tegel/src/components/tabs/navigation-tabs/navigation-tabs-theme-vars.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
Labels: :dark_sunglasses: Mode

#751 fix(slider): add dark mode variables
  tegel/src/components/slider/slider-theme-vars.scss
  tegel/src/components/slider/slider.scss
  tegel/src/components/slider/slider.tsx
Labels: :dark_sunglasses: Mode

#783 Card mode variant rename
  tegel/src/components/card/card-theme-vars.scss
  tegel/src/components/card/card.stories.tsx
Labels: :dark_sunglasses: Mode

#785 Message rename mode variant
  tegel/src/components/message/message-theme-vars.scss
  tegel/src/components/message/message.scss
  tegel/src/components/message/message.stories.tsx
Labels: :dark_sunglasses: Mode

#781 feat(dropdown-native): correct styling for disabled dropdown
  components/src/components/dropdown/dropdown-select.scss
  components/src/components/dropdown/dropdown.stories.js
  tegel/src/components/dropdown/dropdown-select.scss
Labels: 🪲 bug, 🚀 improvement, 📦 @scania/components, 🧱 @scania/tegel

#789 style(storybook): removed keyboard shortcuts
  tegel/.storybook/preview.js
Labels: 📚 docs

#782 feat(inline tabs): child element
  tegel/src/components/tabs/inline-tabs-default/inline-tab/inline-tab.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tab/inline-tab.tsx
  tegel/src/components/tabs/inline-tabs-default/inline-tab/readme.md
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🆕 feature, 🚀 improvement, 🔧 component

#778 Improve popover API for frameworks
  tegel/src/components/popover-canvas/popover-canvas.stories.tsx
  tegel/src/components/popover-canvas/popover-canvas.tsx
  tegel/src/components/popover-canvas/readme.md
  tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
  tegel/src/components/popover-menu/popover-menu.stories.tsx
  tegel/src/components/popover-menu/popover-menu.tsx
  tegel/src/components/popover-menu/readme.md
  tegel/src/components/tooltip/readme.md
  tegel/src/components/tooltip/tooltip.stories.tsx
  tegel/src/components/tooltip/tooltip.tsx
Labels: 🆕 feature, 🚀 improvement

#788 Textarea mode variant 3118
  tegel/src/components/icon/readme.md
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea-theme-vars.scss
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textarea/textarea.stories.tsx
  tegel/src/components/textarea/textarea.tsx
Labels: :dark_sunglasses: Mode

#784 Accordion mode variant rename
  tegel/src/components/accordion/accordion-theme-vars.scss
  tegel/src/components/accordion/accordion.stories.tsx
  tegel/src/components/accordion/accordion.tsx
  tegel/src/components/accordion/readme.md
Labels: :dark_sunglasses: Mode

#786 Button mode variant
  tegel/src/components/button/button-component.tsx
  tegel/src/components/button/button-native.stories.tsx
  tegel/src/components/button/button-theme-vars.scss
  tegel/src/components/button/button-webcomponent.stories.tsx
  tegel/src/components/button/button.scss
  tegel/src/components/button/readme.md
  tegel/src/components/card/card.stories.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: :dark_sunglasses: Mode

#793 fix(card): fix divider class
  tegel/src/components/card/card.scss
  tegel/src/components/card/card.stories.tsx
Labels: 🪲 bug

#804 fix(divider): fix height/width bug in sb
  tegel/src/components/divider/divider.stories.tsx
Labels: 🪲 bug

#805 fix(): dark mode default in divider, footer, header, side-menu and sl…
  tegel/src/components/divider/divider-theme-vars.scss
  tegel/src/components/footer/footer-theme-vars.scss
  tegel/src/components/header/header-theme-vars.scss
  tegel/src/components/side-menu/side-menu-theme-vars.scss
  tegel/src/components/slider/slider-theme-vars.scss
Labels: 🪲 bug

#802 chore(pull request): updated PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🚀 improvement

#809 fix(tooltip): moved comment out of element to not break story
  tegel/src/components/tooltip/tooltip.stories.tsx
Labels: 🪲 bug, 📚 docs
