Repository scania-digital-design-system/sdds, pull requests merged in 2023-02, with the labels that each got.

#792 feat(toggle): webcomponent
  tegel/src/components/toggle/readme.md
  tegel/src/components/toggle/sdds-toggle.scss
  tegel/src/components/toggle/sdds-toggle.stories.tsx
  tegel/src/components/toggle/sdds-toggle.tsx
  tegel/src/components/toggle/toggle.stories.tsx
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#799 feat(message): webcomponent
  tegel/src/components/icon/readme.md
  tegel/src/components/message/message.stories.tsx
  tegel/src/components/message/readme.md
  tegel/src/components/message/sdds-message.scss
  tegel/src/components/message/sdds-message.stories.tsx
  tegel/src/components/message/sdds-message.tsx
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#806 fix(button): only icon button
  tegel/src/components/button/button-component.tsx
  tegel/src/components/button/button-native.stories.tsx
  tegel/src/components/button/button-webcomponent.stories.tsx
  tegel/src/components/button/button.scss
Labels: 🪲 bug

#813 chore: change default light mode variant to white
  tegel/.storybook/preview.js
Labels: :dark_sunglasses: Mode

#811 fix(textarea & textfield) error state and aligned props
  tegel/src/components/icon/readme.md
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield-theme-vars.scss
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.stories.tsx
  tegel/src/components/textfield/textfield.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🪲 bug, 🚨 breaking, 📚 docs

#817 feat(chip): renamed classes to align with convention
  tegel/src/components/chips/chips.scss
  tegel/src/components/chips/chips.stories.tsx
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking, 🧱 @scania/tegel

#800 feat(block): webcomponent
  tegel/src/components/block/block.stories.tsx
  tegel/src/components/block/readme.md
  tegel/src/components/block/sdds-block.scss
  tegel/src/components/block/sdds-block.stories.tsx
  tegel/src/components/block/sdds-block.tsx
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#787 Textfield mode variants
  tegel/package-lock.json
  tegel/src/components/icon/readme.md
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield-theme-vars.scss
  tegel/src/components/textfield/textfield.scss
  tegel/src/components/textfield/textfield.stories.tsx
  tegel/src/components/textfield/textfield.tsx
Labels: :dark_sunglasses: Mode

#797 Tabs mode variants task
  tegel/src/components/tabs/inline-tabs-default/inline-tabs-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs-default/readme.md
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/readme.md
  tegel/src/components/tabs/navigation-tabs/navigation-tabs-theme-vars.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  tegel/src/components/tabs/navigation-tabs/readme.md
Labels: :dark_sunglasses: Mode

#819 fix(inline-tabs): width of buttons
  components/src/components/tabs/inline-tabs/inline-tabs.stories.js
  components/src/components/tabs/inline-tabs/inline-tabs.tsx
Labels: 🪲 bug, 📦 @scania/components

#794 feat(card): webcomponent
  tegel/src/components/card/card-theme-vars.scss
  tegel/src/components/card/card.scss
  tegel/src/components/card/card.stories.tsx
  tegel/src/components/card/readme.md
  tegel/src/components/card/sdds-card.scss
  tegel/src/components/card/sdds-card.stories.tsx
  tegel/src/components/card/sdds-card.tsx
  tegel/src/stories/assets/image/card-placeholder.png
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#803 feat(toast): webcomponent
  tegel/src/components/icon/readme.md
  tegel/src/components/toast/readme.md
  tegel/src/components/toast/sdds-toast.scss
  tegel/src/components/toast/sdds-toast.stories.tsx
  tegel/src/components/toast/sdds-toast.tsx
  tegel/src/components/toast/toast.scss
  tegel/src/components/toast/toast.stories.tsx
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#812 feat(footer): add mode variant for light mode top part
  tegel/src/components/footer/footer-theme-vars.scss
  tegel/src/components/footer/footer.scss
  tegel/src/components/footer/footer.stories.tsx
Labels: :dark_sunglasses: Mode

#825 fix(dropdown): dark mode broken
  tegel/src/components/dropdown/_dropdown-core.scss
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/dropdown/dropdown-theme-vars.scss
  tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
  tegel/src/components/dropdown/dropdown.scss
  tegel/src/components/dropdown/dropdown.tsx
  tegel/src/components/dropdown/readme.md
Labels: :dark_sunglasses: Mode

#824 Feat(datetime): mode variants task 3188
  tegel/src/components/datetime/datetime-theme-vars.scss
  tegel/src/components/datetime/datetime.scss
  tegel/src/components/datetime/datetime.stories.tsx
  tegel/src/components/datetime/datetime.tsx
  tegel/src/components/datetime/readme.md
Labels: :dark_sunglasses: Mode

#829 fix(toast): refactor events
  tegel/src/components/toast/readme.md
  tegel/src/components/toast/sdds-toast.stories.tsx
  tegel/src/components/toast/sdds-toast.tsx
Labels: 🚀 improvement

#830 fix(banner): refactored events
  tegel/src/components/banner/readme.md
  tegel/src/components/banner/sdds-banner.stories.tsx
  tegel/src/components/banner/sdds-banner.tsx
Labels: 🚀 improvement

#827 build(dark mode): enabled dark mode in production
  tegel/.storybook/main.js
Labels: :dark_sunglasses: Mode

#831 feat(card): refactor events
  tegel/src/components/card/readme.md
  tegel/src/components/card/sdds-card.stories.tsx
  tegel/src/components/card/sdds-card.tsx
Labels: 🚀 improvement

#828 fix(expandable table): safari bug
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss
Labels: 🪲 bug

#826 docs(event): documentation of event naming convention
  tegel/readme.md
  tegel/src/stories/Events/Events.stories.mdx
Labels: 📚 docs

#832 fix(checkbox): remove usused prop - label
  tegel/src/components/checkbox/readme.md
  tegel/src/components/checkbox/sdds-checkbox.tsx
Labels: 🪲 bug

#823 docs: migration docs for dark mode
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 📚 docs, :dark_sunglasses: Mode

#821 fix: mode variant add null and inherit from parent to components
  tegel/src/components/accordion/accordion.tsx
  tegel/src/components/button/button-component.tsx
  tegel/src/components/card/card.stories.tsx
  tegel/src/components/message/message-theme-vars.scss
  tegel/src/components/message/message.stories.tsx
  tegel/src/components/message/readme.md
  tegel/src/components/message/sdds-message.stories.tsx
  tegel/src/components/message/sdds-message.tsx
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
  tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.stories.tsx
  tegel/src/components/textarea/textarea.tsx
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.tsx
Labels: :dark_sunglasses: Mode

#837 build(addons): removed double dark mode addon
  tegel/.storybook/main.js
Labels: 👷🏻build👷🏻‍♀️

#836 fix(banner): renamed linkHref to href
  tegel/src/components/banner/readme.md
  tegel/src/components/banner/sdds-banner.stories.tsx
  tegel/src/components/banner/sdds-banner.tsx
Labels: 🚀 improvement

#839 chore: release 51
  components/package-lock.json
  components/package.json
Labels: 📦 @scania/components, 🎉 release

#838 fix(toggle): darkmode fixes
  tegel/src/components/toggle/sdds-toggle.scss
  tegel/src/components/toggle/sdds-toggle.tsx
  tegel/src/components/toggle/toggle-theme-vars.scss
  tegel/src/components/toggle/toggle.scss
  tegel/src/components/toggle/toggle.stories.tsx
Labels: 🪲 bug, :dark_sunglasses: Mode

#840 fix(badge): visibility prop
  tegel/src/components/badge/badge.stories.tsx
  tegel/src/components/badge/badges.tsx
  tegel/src/components/badge/readme.md
  tegel/src/stories/Migration/Migration.stories.mdx
Labels: 🚀 improvement, 🚨 breaking, 🧱 @scania/tegel

#835 fix(link): renamed linkHref to href
  tegel/src/components/link/readme.md
  tegel/src/components/link/sdds-link.stories.tsx
  tegel/src/components/link/sdds-link.tsx
Labels: 🚀 improvement

#822 feat(data-table): mode variant prop and storybook examples update
  tegel/src/components/data-table/data-table-theme-vars.scss
  tegel/src/components/data-table/native-table.scss
  tegel/src/components/data-table/native-table.stories.tsx
  tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss
  tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
  tegel/src/components/data-table/table-body-row/table-body-row.scss
  tegel/src/components/data-table/table-body-row/table-body-row.tsx
  tegel/src/components/data-table/table-component-basic.stories.tsx
  tegel/src/components/data-table/table-component-batch-actions.stories.tsx
  tegel/src/components/data-table/table-component-custom-width.stories.tsx
  tegel/src/components/data-table/table-component-event-listeners.stories.tsx
  tegel/src/components/data-table/table-component-expandable-rows.stories.tsx
  tegel/src/components/data-table/table-component-filtering.stories.tsx
  tegel/src/components/data-table/table-component-multiselect.stories.tsx
  tegel/src/components/data-table/table-component-pagination.stories.tsx
  tegel/src/components/data-table/table-component-sorting.stories.tsx
  tegel/src/components/data-table/table-footer/table-footer.tsx
  tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
  tegel/src/components/data-table/table-header/table-header.tsx
  tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
  tegel/src/components/data-table/table/readme.md
  tegel/src/components/data-table/table/table.tsx
Labels: 🔧 component, 🧑‍🎨 design, 🧱 @scania/tegel

#842 fix(slider): refactor event names
  tegel/src/components/icon/readme.md
  tegel/src/components/slider/readme.md
  tegel/src/components/slider/slider.stories.tsx
  tegel/src/components/slider/slider.tsx
Labels: 🚀 improvement, 🚨 breaking

#845 fix: null not valid value for mode variant prop
  tegel/src/components/block/sdds-block.tsx
  tegel/src/components/datetime/datetime.tsx
  tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
Labels: :dark_sunglasses: Mode

#808 feat(radio button): web component
  tegel/src/components/radio-button/radio-button-component.scss
  tegel/src/components/radio-button/radio-button-component.stories.tsx
  tegel/src/components/radio-button/radio-button-theme-vars.scss
  tegel/src/components/radio-button/radio-button.stories.tsx
  tegel/src/components/radio-button/radio-button.tsx
  tegel/src/components/radio-button/readme.md
Labels: 🆕 feature, 🔧 component, 🧑‍🎨 design, 🧱 @scania/tegel

#851 fix(radio button): align event names
  tegel/src/components/radio-button/radio-button-component.stories.tsx
  tegel/src/components/radio-button/radio-button.tsx
  tegel/src/components/radio-button/readme.md
Labels: 🚀 improvement

#847 fix(textfield): refactored event names
  tegel/src/components/textfield/readme.md
  tegel/src/components/textfield/textfield.stories.tsx
  tegel/src/components/textfield/textfield.tsx
Labels: 🚀 improvement, 🚨 breaking

#849 fix(checkbox): refactor event names
  tegel/src/components/checkbox/readme.md
  tegel/src/components/checkbox/sdds-checkbox.stories.tsx
  tegel/src/components/checkbox/sdds-checkbox.tsx
Labels: 🚀 improvement, 🚨 breaking

#848 fix: change sdds-theme to sdds-mode
  tegel/.storybook/preview.js
  tegel/src/components/accordion/accordion-theme-vars.scss
  tegel/src/components/banner/banner-theme-vars.scss
  tegel/src/components/block/block-theme-vars.scss
  tegel/src/components/breadcrumb/breadcrumb-theme-vars.scss
  tegel/src/components/button/button-theme-vars.scss
  tegel/src/components/card/card-theme-vars.scss
  tegel/src/components/checkbox/checkbox-theme-vars.scss
  tegel/src/components/chips/chips-theme-vars.scss
  tegel/src/components/data-table/data-table-theme-vars.scss
  tegel/src/components/datetime/datetime-theme-vars.scss
  tegel/src/components/divider/divider-theme-vars.scss
  tegel/src/components/dropdown/dropdown-select.scss
  tegel/src/components/dropdown/dropdown-theme-vars.scss
  tegel/src/components/footer/footer-theme-vars.scss
  tegel/src/components/header/header-theme-vars.scss
  tegel/src/components/link/link-theme-vars.scss
  tegel/src/components/message/message-theme-vars.scss
  tegel/src/components/modal/modal-theme-vars.scss
  tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss
  tegel/src/components/popover-menu/popover-menu-theme-vars.scss
  tegel/src/components/radio-button/radio-button-theme-vars.scss
  tegel/src/components/side-menu/side-menu-theme-vars.scss
  tegel/src/components/slider/slider-theme-vars.scss
  tegel/src/components/stepper/stepper-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-default/inline-tabs-theme-vars.scss
  tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
  tegel/src/components/tabs/navigation-tabs/navigation-tabs-theme-vars.scss
  tegel/src/components/textarea/textarea-theme-vars.scss
  tegel/src/components/textfield/textfield-theme-vars.scss
  tegel/src/components/toast/toast-theme-vars.scss
  tegel/src/components/toggle/toggle-theme-vars.scss
  tegel/src/components/tooltip/tooltip-theme-vars.scss
  tegel/src/global/global.scss
  theme/light/src/_reboot.scss
Labels: :dark_sunglasses: Mode

#843 fix(textarea): refactor event names
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.stories.tsx
  tegel/src/components/textarea/textarea.tsx
Labels: 🚀 improvement, 🚨 breaking

#854 build: Tegel release 51
  tegel/package-lock.json
  tegel/package.json
Labels: 👷🏻build👷🏻‍♀️, 🎉 release, 🧱 @scania/tegel

#853 fix(accordion): events name update
  tegel/src/components/accordion/accordion-item/accordion-item.tsx
  tegel/src/components/accordion/accordion-item/readme.md
  tegel/src/components/accordion/accordion.stories.tsx
Labels: 🚀 improvement, 🔧 component, 🧱 @scania/tegel

#857 build(release script): created a small release script for tegel
  tegel/tegel-release.sh
Labels: 👷🏻build👷🏻‍♀️

#864 fix(badge): standardise order of controls in Storybook
  tegel/src/components/badge/badge.stories.tsx
Labels: 🚀 improvement, 🧱 @scania/tegel

#863 fix(accordion): standardise order of Storybook controls
  tegel/src/components/accordion/accordion.stories.tsx
Labels: 🚀 improvement, 🧱 @scania/tegel

#762 feat(stepper): webcomponent
  tegel/src/components/icon/readme.md
  tegel/src/components/stepper/readme.md
  tegel/src/components/stepper/sdds-stepper.scss
  tegel/src/components/stepper/sdds-stepper.stories.ts
  tegel/src/components/stepper/sdds-stepper.tsx
  tegel/src/components/stepper/stepper-item/readme.md
  tegel/src/components/stepper/stepper-item/sdds-stepper-item.scss
  tegel/src/components/stepper/stepper-item/sdds-stepper-item.tsx
  tegel/src/components/stepper/stepper-vars.scss
  tegel/src/components/stepper/stepper.scss
  tegel/src/components/stepper/stepper.stories.tsx
  tegel/src/global/global.scss
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#856 fix(toggle): refactor event names
  tegel/src/components/toggle/readme.md
  tegel/src/components/toggle/sdds-toggle.stories.tsx
  tegel/src/components/toggle/sdds-toggle.tsx
Labels: 🚀 improvement

#866 fix(banner): update control descriptions in Storybook
  tegel/src/components/banner/banner.stories.tsx
  tegel/src/components/banner/sdds-banner.stories.tsx
Labels: 🚀 improvement, 🧱 @scania/tegel

#865 fix(textarea): correct disabled styling
  tegel/src/components/textarea/textarea-vars.scss
Labels: :dark_sunglasses: Mode

#807 feat(footer): webcomponent
  tegel/src/components/footer/footer-vars.scss
  tegel/src/components/footer/footer.stories.tsx
  tegel/src/components/footer/webcomponent/readme.md
  tegel/src/components/footer/webcomponent/sdds-footer-link-group/readme.md
  tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.scss
  tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
  tegel/src/components/footer/webcomponent/sdds-footer-link/readme.md
  tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.scss
  tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
  tegel/src/components/footer/webcomponent/sdds-footer.scss
  tegel/src/components/footer/webcomponent/sdds-footer.stories.tsx
  tegel/src/components/footer/webcomponent/sdds-footer.tsx
  tegel/src/components/icon/readme.md
Labels: 🆕 feature, 🔧 component, 🧱 @scania/tegel

#858 feat(textarea): added prop for no minwidth
  components/src/components/textarea/readme.md
  components/src/components/textarea/textarea.scss
  components/src/components/textarea/textarea.tsx
  tegel/src/components/textarea/readme.md
  tegel/src/components/textarea/textarea.scss
  tegel/src/components/textarea/textarea.stories.tsx
  tegel/src/components/textarea/textarea.tsx
Labels: 🚀 improvement, 📦 @scania/components, 🧱 @scania/tegel
